# Generated by Django 2.2.2 on 2019-11-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardkingdomanalytics',
            name='last_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
