# Generated by Django 2.2.2 on 2019-11-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_cardkingdomanalytics_last_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardkingdomanalytics',
            name='last_percent_change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
