# Generated by Django 2.2.2 on 2019-11-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0003_cardkingdomanalytics_last_percent_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardkingdomanalytics',
            name='total_days_without_decrease',
            field=models.IntegerField(default=0),
        ),
    ]
