# Generated by Django 3.0.5 on 2020-10-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Safe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('current_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('withdrawal', models.CharField(default='0', max_length=12)),
                ('deposit', models.CharField(default='0', max_length=12)),
                ('reason', models.CharField(choices=[('', ''), ('trade_in', 'trade in'), ('restock', 'safe restock'), ('daily_deposit', 'daily deposit'), ('balance', 'safe balance'), ('cash_withdrawal', 'cash withdrawal')], default='', max_length=255)),
                ('manager_initials', models.CharField(default='', max_length=255)),
                ('seller_name', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Safe',
            },
        ),
    ]
