# Generated by Django 3.0.5 on 2020-10-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20201026_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='safe',
            old_name='current_total',
            new_name='balance',
        ),
    ]
