# Generated by Django 3.0.5 on 2020-10-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20201026_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safe',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
