# Generated by Django 3.0.5 on 2020-10-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_auto_20201026_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safe',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
