# Generated by Django 2.0 on 2018-08-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20180821_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpreordersready',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='preordersready',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
    ]
