# Generated by Django 2.0 on 2018-08-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20180821_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='wishlist',
        ),
        migrations.RemoveField(
            model_name='historicalcustomer',
            name='wishlist',
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Store Credit'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Store Credit'),
        ),
    ]
