# Generated by Django 2.0 on 2018-08-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20180821_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcustomer',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
