# Generated by Django 2.0 on 2018-08-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20180821_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcustomer',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
