# Generated by Django 2.0 on 2018-08-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20180822_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='historicalcustomer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='historicalcustomer',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=200),
        ),
    ]
