# Generated by Django 2.0 on 2018-08-25 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_auto_20180825_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='contact_type',
            field=models.CharField(default='', max_length=50, verbose_name='Contact by'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 25, 5, 18, 17, 256507), verbose_name='Order Placed'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='phone',
            field=models.CharField(default='', max_length=50, verbose_name='Phone Number'),
        ),
    ]
