# Generated by Django 2.0 on 2018-09-11 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_auto_20180910_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='Name Unknown', max_length=60)),
                ('release_date', models.CharField(default='Unknown', max_length=25, verbose_name='Releasee Date')),
                ('price', models.CharField(default='None', max_length=20, verbose_name='MSRP')),
            ],
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 16, 0, 35, 1828), verbose_name='Order Placed'),
        ),
    ]
