# Generated by Django 2.0 on 2018-09-11 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_auto_20180911_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasedproducts',
            name='link',
            field=models.URLField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 16, 22, 47, 216762), verbose_name='Order Placed'),
        ),
    ]
