# Generated by Django 2.0 on 2018-09-15 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_auto_20180915_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 15, 10, 29, 20, 496713), verbose_name='Order Placed'),
        ),
    ]
