# Generated by Django 2.0 on 2018-09-15 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_auto_20180915_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 15, 11, 30, 26, 508509), verbose_name='Order Placed'),
        ),
    ]
