# Generated by Django 2.0 on 2018-09-17 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0033_auto_20180915_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 11, 27, 18, 498089), verbose_name='Order Placed'),
        ),
    ]
