# Generated by Django 2.0 on 2018-09-19 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0037_auto_20180918_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 19, 28, 47, 24459), verbose_name='Order Placed'),
        ),
    ]
