# Generated by Django 2.0 on 2018-10-11 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0042_auto_20181002_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcustomer',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 13, 7, 22, 264299), verbose_name='Order Placed'),
        ),
    ]
