# Generated by Django 2.0 on 2018-10-12 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0048_auto_20181012_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tournament_entry',
            field=models.CharField(choices=[('none', 'none'), ('mtg locals', 'mtg locals'), ('yugioh locals', 'yugioh locals')], default='none', max_length=255, verbose_name='Subtract Event Entry'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tournament_results_credit',
            field=models.CharField(choices=[('none', 'none'), ('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('5', '30'), ('35', '35'), ('40', '40')], default='none', max_length=255, verbose_name='Add Event Credit'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='tournament_entry',
            field=models.CharField(choices=[('none', 'none'), ('mtg locals', 'mtg locals'), ('yugioh locals', 'yugioh locals')], default='none', max_length=255, verbose_name='Subtract Event Entry'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='tournament_results_credit',
            field=models.CharField(choices=[('none', 'none'), ('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('5', '30'), ('35', '35'), ('40', '40')], default='none', max_length=255, verbose_name='Add Event Credit'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 12, 14, 54, 24, 204885), verbose_name='Order Placed'),
        ),
    ]
