# Generated by Django 2.0 on 2018-10-25 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0049_auto_20181012_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 14, 39, 7, 718228), verbose_name='Order Placed'),
        ),
    ]
