# Generated by Django 2.0 on 2018-11-15 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0052_auto_20181114_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 19, 59, 12, 835886), verbose_name='Order Placed'),
        ),
    ]
