# Generated by Django 2.0 on 2018-11-15 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0054_auto_20181114_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 20, 27, 19, 757388), verbose_name='Order Placed'),
        ),
    ]
