# Generated by Django 2.0 on 2018-11-15 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0065_auto_20181114_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 21, 6, 58, 197468), verbose_name='Order Placed'),
        ),
    ]
