# Generated by Django 2.1.4 on 2018-12-22 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0068_auto_20181222_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 17, 55, 57, 904993), verbose_name='Order Placed'),
        ),
    ]
