# Generated by Django 2.1.4 on 2019-01-04 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0074_auto_20181231_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 3, 20, 19, 6, 263046), verbose_name='Order Placed'),
        ),
    ]
