# Generated by Django 2.1.4 on 2019-01-04 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0075_auto_20190103_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 3, 20, 40, 19, 243087), verbose_name='Order Placed'),
        ),
    ]
