# Generated by Django 2.1.4 on 2019-01-08 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0076_auto_20190103_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 8, 13, 49, 50, 963908), verbose_name='Order Placed'),
        ),
    ]
