# Generated by Django 2.1.4 on 2019-01-19 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0077_auto_20190108_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 19, 3, 10, 22, 577828), verbose_name='Order Placed'),
        ),
    ]
