# Generated by Django 2.1.4 on 2019-01-23 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0080_auto_20190119_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 11, 56, 25, 853170), verbose_name='Order Placed'),
        ),
    ]
