# Generated by Django 2.1.4 on 2019-01-23 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0081_auto_20190123_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 12, 2, 24, 97295), verbose_name='Order Placed'),
        ),
    ]
