# Generated by Django 2.1.4 on 2019-01-23 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0085_auto_20190123_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 12, 53, 19, 974073), verbose_name='Order Placed'),
        ),
    ]
