# Generated by Django 2.1.4 on 2019-01-23 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0097_auto_20190123_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 16, 11, 19, 199089), verbose_name='Order Placed'),
        ),
    ]
