# Generated by Django 2.1.4 on 2019-02-06 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0103_auto_20190206_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 14, 11, 32, 333628), verbose_name='Order Placed'),
        ),
    ]
