# Generated by Django 2.1.4 on 2019-02-12 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0106_auto_20190211_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 11, 23, 7, 5, 298270), verbose_name='Order Placed'),
        ),
    ]
