# Generated by Django 2.1.4 on 2019-02-16 13:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0108_auto_20190213_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only letters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only letters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 16, 8, 46, 15, 426430), verbose_name='Order Placed'),
        ),
    ]
