# Generated by Django 2.1.4 on 2019-02-19 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0112_auto_20190218_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 22, 24, 17, 594240), verbose_name='Order Placed'),
        ),
    ]
