# Generated by Django 2.1.4 on 2019-02-19 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0114_auto_20190219_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 19, 13, 3, 10, 52775), verbose_name='Order Placed'),
        ),
    ]
