# Generated by Django 2.1.4 on 2019-02-20 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0116_auto_20190220_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 15, 52, 50, 945454), verbose_name='Order Placed'),
        ),
    ]
