# Generated by Django 2.1.4 on 2019-02-20 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0117_auto_20190220_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 17, 25, 46, 947008), verbose_name='Order Placed'),
        ),
    ]
