# Generated by Django 2.1.4 on 2019-02-21 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0119_auto_20190220_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 14, 45, 13, 338427), verbose_name='Order Placed'),
        ),
    ]
