# Generated by Django 2.1.4 on 2019-02-21 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0120_auto_20190221_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 15, 10, 43, 39118), verbose_name='Order Placed'),
        ),
    ]
