# Generated by Django 2.1.4 on 2019-02-26 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0123_auto_20190225_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 10, 4, 25, 714016), verbose_name='Order Placed'),
        ),
    ]
