# Generated by Django 2.1.4 on 2019-02-26 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0124_auto_20190226_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 10, 15, 38, 331544), verbose_name='Order Placed'),
        ),
    ]
