# Generated by Django 2.1.4 on 2019-02-26 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0126_auto_20190226_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 11, 28, 51, 6045), verbose_name='Order Placed'),
        ),
    ]
