# Generated by Django 2.1.4 on 2019-02-26 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0127_auto_20190226_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 16, 29, 22, 491918), verbose_name='Order Placed'),
        ),
    ]
