# Generated by Django 2.1.4 on 2019-02-28 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0133_auto_20190227_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 8, 18, 51, 542643), verbose_name='Order Placed'),
        ),
    ]
