# Generated by Django 2.1.4 on 2019-03-01 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0134_auto_20190228_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 22, 29, 40, 605220), verbose_name='Order Placed'),
        ),
    ]
