# Generated by Django 2.1.4 on 2019-03-02 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0135_auto_20190228_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 13, 44, 55, 825890), verbose_name='Order Placed'),
        ),
    ]
