# Generated by Django 2.1.4 on 2019-03-03 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0136_auto_20190302_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 10, 48, 39, 735130), verbose_name='Order Placed'),
        ),
    ]
