# Generated by Django 2.1.4 on 2019-03-03 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0137_auto_20190303_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 16, 53, 50, 715930), verbose_name='Order Placed'),
        ),
    ]
