# Generated by Django 2.1.4 on 2019-03-20 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0146_auto_20190320_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 17, 33, 34, 238510), verbose_name='Order Placed'),
        ),
    ]
