# Generated by Django 2.1.4 on 2019-03-23 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0148_auto_20190320_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 13, 12, 4, 1073), verbose_name='Order Placed'),
        ),
    ]
