# Generated by Django 2.1.4 on 2019-03-25 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0150_auto_20190325_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 25, 16, 16, 26, 893573), verbose_name='Order Placed'),
        ),
    ]
