# Generated by Django 2.1.4 on 2019-03-30 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0151_auto_20190325_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemizedPreorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('expansion', models.CharField(default='', max_length=255)),
                ('item_type', models.CharField(default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available', models.BooleanField(default=True)),
                ('image_url', models.CharField(default='', max_length=255)),
                ('product_id', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 30, 14, 59, 18, 32446), verbose_name='Order Placed'),
        ),
    ]
