# Generated by Django 2.1.4 on 2019-04-01 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0154_auto_20190401_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemizedpreorder',
            name='color',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='itemizedpreorder',
            name='rarity',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 17, 9, 33, 691615), verbose_name='Order Placed'),
        ),
    ]
