# Generated by Django 2.1.4 on 2019-04-02 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0155_auto_20190401_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 2, 16, 52, 40, 395849), verbose_name='Order Placed'),
        ),
    ]
