# Generated by Django 2.1.4 on 2019-04-04 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0156_auto_20190402_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemizedpreorder',
            name='card_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 4, 9, 24, 40, 470495), verbose_name='Order Placed'),
        ),
    ]
