# Generated by Django 2.1.4 on 2019-04-12 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0163_auto_20190411_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 20, 58, 12, 894927), verbose_name='Order Placed'),
        ),
    ]
