# Generated by Django 2.1.4 on 2019-04-12 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0165_auto_20190411_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 22, 48, 29, 714392), verbose_name='Order Placed'),
        ),
    ]
