# Generated by Django 2.1.4 on 2019-04-12 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0172_auto_20190412_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 12, 55, 23, 893475), verbose_name='Order Placed'),
        ),
    ]
