# Generated by Django 2.2.2 on 2019-07-26 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0183_auto_20190725_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 25, 23, 16, 3, 870325), verbose_name='Order Placed'),
        ),
    ]
