# Generated by Django 2.2.2 on 2019-08-08 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0186_auto_20190729_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 17, 13, 32, 681143), verbose_name='Order Placed'),
        ),
    ]
