# Generated by Django 2.2.2 on 2019-08-12 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0188_auto_20190812_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 12, 15, 46, 54, 243004), verbose_name='Order Placed'),
        ),
    ]
