# Generated by Django 2.2.2 on 2019-08-18 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0189_auto_20190812_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 18, 11, 9, 25, 823072), verbose_name='Order Placed'),
        ),
    ]
