# Generated by Django 2.2.2 on 2019-08-18 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0190_auto_20190818_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 18, 17, 13, 23, 716832), verbose_name='Order Placed'),
        ),
    ]
