# Generated by Django 2.2.2 on 2019-08-19 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0192_auto_20190819_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 19, 12, 24, 37, 788877), verbose_name='Order Placed'),
        ),
    ]
