# Generated by Django 2.2.2 on 2019-09-07 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0193_auto_20190819_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 7, 13, 39, 27, 726440), verbose_name='Order Placed'),
        ),
    ]
