# Generated by Django 2.2.2 on 2019-09-14 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0197_auto_20190913_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 13, 21, 7, 21, 242662), verbose_name='Order Placed'),
        ),
    ]
