# Generated by Django 2.2.2 on 2019-11-16 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0208_auto_20191109_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 11, 46, 18, 966297), verbose_name='Order Placed'),
        ),
    ]
