# Generated by Django 2.2.2 on 2019-11-26 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0215_auto_20191123_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 20, 15, 51, 796496), verbose_name='Order Placed'),
        ),
    ]
