# Generated by Django 2.2.2 on 2019-11-30 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0217_auto_20191127_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 30, 15, 45, 57, 932702), verbose_name='Order Placed'),
        ),
    ]
