# Generated by Django 2.2.2 on 2019-11-30 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0218_auto_20191130_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 30, 16, 18, 51, 146694), verbose_name='Order Placed'),
        ),
    ]
