# Generated by Django 2.2.2 on 2019-11-30 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0219_auto_20191130_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 30, 17, 22, 10, 615573), verbose_name='Order Placed'),
        ),
    ]
