# Generated by Django 2.2.2 on 2019-12-09 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0220_auto_20191130_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 15, 42, 55, 898721), verbose_name='Order Placed'),
        ),
    ]
