# Generated by Django 2.2.2 on 2019-12-18 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0222_auto_20191218_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 17, 34, 33, 738344), verbose_name='Order Placed'),
        ),
    ]
