# Generated by Django 2.2.2 on 2019-12-19 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0225_auto_20191218_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, verbose_name='last_credit'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='last_credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, verbose_name='last_credit'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 19, 24, 32, 330572), verbose_name='Order Placed'),
        ),
    ]
