# Generated by Django 2.2.2 on 2019-12-31 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0227_auto_20191218_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 19, 55, 54, 326938), verbose_name='Order Placed'),
        ),
    ]
