# Generated by Django 2.2.2 on 2019-12-31 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0229_auto_20191231_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 14, 28, 17, 307981), verbose_name='Order Placed'),
        ),
    ]
