# Generated by Django 2.2.2 on 2020-01-03 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0230_auto_20191231_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 16, 3, 51, 383738), verbose_name='Order Placed'),
        ),
    ]
