# Generated by Django 2.2.2 on 2020-01-04 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0231_auto_20200103_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 20, 4, 14, 65568), verbose_name='Order Placed'),
        ),
    ]
