# Generated by Django 2.2.2 on 2020-01-15 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0238_auto_20200115_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 15, 16, 55, 58, 695001), verbose_name='Order Placed'),
        ),
    ]
