# Generated by Django 2.2.2 on 2020-01-20 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0240_auto_20200120_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 17, 24, 30, 759395), verbose_name='Order Placed'),
        ),
    ]
