# Generated by Django 2.2.2 on 2020-01-30 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0241_auto_20200120_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 19, 33, 17, 96042), verbose_name='Order Placed'),
        ),
    ]
