# Generated by Django 2.2.2 on 2020-01-30 00:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0242_auto_20200129_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasedproducts',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 19, 49, 27, 877706), verbose_name='Order Placed'),
        ),
    ]
