# Generated by Django 2.2.2 on 2020-02-06 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0246_auto_20200131_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 6, 12, 34, 14, 813257), verbose_name='Order Placed'),
        ),
    ]
