# Generated by Django 2.2.2 on 2020-02-07 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0247_auto_20200206_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='second_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='second_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 6, 20, 26, 16, 525924), verbose_name='Order Placed'),
        ),
    ]
