# Generated by Django 2.2.2 on 2020-02-09 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0248_auto_20200206_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 8, 21, 6, 19, 452150), verbose_name='Order Placed'),
        ),
    ]
