# Generated by Django 2.2.2 on 2020-02-13 00:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0250_auto_20200208_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only letters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='name',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only letters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 12, 19, 54, 57, 495137), verbose_name='Order Placed'),
        ),
    ]
