# Generated by Django 2.2.2 on 2020-02-14 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0251_auto_20200212_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_subscriber',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='email_subscriber',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='shipping_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 16, 26, 4, 458973), verbose_name='Order Placed'),
        ),
    ]
