# Generated by Django 2.2.2 on 2020-02-15 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0252_auto_20200214_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email_subscriber',
            new_name='email_subscriber_all',
        ),
        migrations.RenameField(
            model_name='historicalcustomer',
            old_name='email_subscriber',
            new_name='email_subscriber_all',
        ),
        migrations.AddField(
            model_name='customer',
            name='email_subscriber_buylist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_subscriber_events',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='email_subscriber_buylist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='email_subscriber_events',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 19, 16, 39, 695428), verbose_name='Order Placed'),
        ),
    ]
