# Generated by Django 2.2.2 on 2020-02-18 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0253_auto_20200214_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_subscriber_new_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='email_subscriber_new_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 20, 0, 17, 147700), verbose_name='Order Placed'),
        ),
    ]
