# Generated by Django 2.2.2 on 2020-02-19 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0254_auto_20200217_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 13, 5, 48, 878253), verbose_name='Order Placed'),
        ),
    ]
