# Generated by Django 2.2.2 on 2020-02-19 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0257_auto_20200219_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 16, 0, 25, 770264), verbose_name='Order Placed'),
        ),
    ]
