# Generated by Django 2.2.2 on 2020-02-24 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0259_auto_20200219_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 12, 51, 19, 400141), verbose_name='Order Placed'),
        ),
    ]
