# Generated by Django 2.2.2 on 2020-02-24 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0261_auto_20200224_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 14, 54, 29, 325037), verbose_name='Order Placed'),
        ),
    ]
