# Generated by Django 2.2.2 on 2020-02-24 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0262_auto_20200224_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 15, 19, 48, 986377), verbose_name='Order Placed'),
        ),
    ]
