# Generated by Django 2.2.2 on 2020-02-24 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0263_auto_20200224_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 16, 53, 28, 259059), verbose_name='Order Placed'),
        ),
    ]
