# Generated by Django 2.2.2 on 2020-02-24 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0264_auto_20200224_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 17, 57, 34, 467261), verbose_name='Order Placed'),
        ),
    ]
