# Generated by Django 2.2.2 on 2020-03-24 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0265_auto_20200224_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 14, 47, 53, 517486), verbose_name='Order Placed'),
        ),
    ]
