# Generated by Django 2.2.2 on 2020-04-14 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0266_auto_20200324_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 12, 4, 45, 441751), verbose_name='Order Placed'),
        ),
    ]
