# Generated by Django 2.2.2 on 2020-04-14 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0267_auto_20200414_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 12, 53, 0, 901943), verbose_name='Order Placed'),
        ),
    ]
