# Generated by Django 2.2.2 on 2020-04-24 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0268_auto_20200414_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 6, 19, 17, 251080), verbose_name='Order Placed'),
        ),
    ]
