# Generated by Django 3.0.5 on 2020-05-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0162_auto_20200507_1808'),
        ('customer', '0270_auto_20200427_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wishlist',
            field=models.ManyToManyField(to='engine.MTG'),
        ),
    ]
