# Generated by Django 3.0.5 on 2020-05-13 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0271_customer_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='wishlist',
        ),
    ]
