# Generated by Django 3.0.5 on 2020-08-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0279_auto_20200706_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='orders',
            field=models.TextField(blank=True, default=''),
        ),
    ]
