# Generated by Django 3.0.5 on 2020-09-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0280_auto_20200824_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='buylist_submissions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='buylist_submissions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
