# Generated by Django 3.0.5 on 2020-10-24 01:19

from django.db import migrations, models
import validators.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0282_storecredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='clear_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='transaction',
            field=models.CharField(choices=[('', ''), ('other', 'other'), ('mtg', 'mtg'), ('pokemon', 'pokemon'), ('supplies', 'supplies'), ('yugioh', 'yugioh')], default='', max_length=255, validators=[validators.model_validators.cannot_be_empty]),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='clear_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='transaction',
            field=models.CharField(choices=[('', ''), ('other', 'other'), ('mtg', 'mtg'), ('pokemon', 'pokemon'), ('supplies', 'supplies'), ('yugioh', 'yugioh')], default='', max_length=255, validators=[validators.model_validators.cannot_be_empty]),
        ),
    ]
