# Generated by Django 3.0.5 on 2020-10-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0283_auto_20201023_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecredit',
            name='transaction_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
