# Generated by Django 2.2.2 on 2020-02-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('name', models.CharField(default='', max_length=30)),
                ('order_number', models.CharField(blank=True, default='', max_length=15)),
                ('message', models.TextField()),
                ('reply', models.TextField()),
                ('subject', models.CharField(default='', max_length=50)),
                ('message_created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
