# Generated by Django 2.2.2 on 2020-02-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20200219_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeremail',
            name='replied_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
