# Generated by Django 2.1.4 on 2019-02-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default='', max_length=100)),
                ('order_channel_type', models.CharField(default='', max_length=100)),
                ('order_status_type', models.CharField(default='', max_length=100)),
                ('order_delivery_type', models.CharField(default='', max_length=100)),
                ('is_direct', models.BooleanField()),
                ('international', models.BooleanField()),
                ('presale_status_type', models.CharField(default='', max_length=100)),
                ('order_date', models.DateField()),
                ('modified_on_date', models.DateField()),
                ('customer_token', models.CharField(default='', max_length=100)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('shipping_first_name', models.CharField(default='', max_length=100)),
                ('shipping_last_name', models.CharField(default='', max_length=100)),
                ('address_1', models.CharField(default='', max_length=100)),
                ('address_2', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('postal_code', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('product_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('gross', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('net', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('ordered_items', models.TextField()),
            ],
        ),
    ]
