# Generated by Django 2.1.4 on 2019-02-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190211_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='category',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
