# Generated by Django 2.1.4 on 2019-02-19 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20190218_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworders',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
