# Generated by Django 2.1.4 on 2019-02-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20190227_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupname',
            name='category',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
