# Generated by Django 2.1.4 on 2019-02-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20190227_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='update_inventory_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventoryanalytics',
            name='check_date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
