# Generated by Django 2.1.4 on 2019-03-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20190228_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryanalytics',
            name='total_of_others',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryanalytics',
            name='total_of_others_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='neworders',
            name='is_direct',
            field=models.BooleanField(default=False),
        ),
    ]
