# Generated by Django 2.1.4 on 2019-03-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20190228_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryanalytics',
            name='check_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date / Time'),
        ),
    ]
