# Generated by Django 2.2.2 on 2019-09-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_auto_20190819_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonPriceExclusions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('expansion', models.CharField(blank=True, default='', max_length=255)),
                ('condition', models.CharField(blank=True, default='', max_length=255)),
                ('is_foil', models.BooleanField(blank=True, default=False)),
                ('sku', models.CharField(default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
