# Generated by Django 2.2.2 on 2019-09-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0005_amazonpriceexclusions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonpriceexclusions',
            name='sku',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
