# Generated by Django 2.2.2 on 2019-08-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonLiveInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='', max_length=255)),
                ('old_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_time_change', models.DateTimeField(auto_now=True)),
                ('time_check_delta', models.DateTimeField()),
            ],
        ),
    ]
