# Generated by Django 2.2.2 on 2019-08-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonliveinventory',
            name='time_check_delta',
            field=models.CharField(default='', max_length=255),
        ),
    ]
