# Generated by Django 2.2.2 on 2019-08-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_auto_20190818_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('feed_id', models.CharField(default='', max_length=255)),
                ('feed_successful_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
