# Generated by Django 2.2.2 on 2019-08-19 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_feedsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedsubmission',
            name='feed_created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedsubmission',
            name='feed_successful_on',
            field=models.DateTimeField(),
        ),
    ]
