# Generated by Django 2.2.2 on 2019-11-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0006_auto_20190913_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonpriceexclusions',
            name='price_metrics',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
