# Generated by Django 2.2.2 on 2019-11-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0007_amazonpriceexclusions_price_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonpriceexclusions',
            name='exclude',
            field=models.BooleanField(default=True),
        ),
    ]
