# Generated by Django 2.2.2 on 2020-01-15 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_amazonpriceexclusions_exclude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazonpriceexclusions',
            old_name='price',
            new_name='min_price',
        ),
    ]
