# Generated by Django 2.2.2 on 2020-01-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0009_auto_20200115_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonpriceexclusions',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
