# Generated by Django 3.0.5 on 2020-08-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0010_amazonpriceexclusions_max_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonpriceexclusions',
            name='date_time_changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
