# Generated by Django 3.0.5 on 2020-08-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0011_amazonpriceexclusions_date_time_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonpriceexclusions',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
