# Generated by Django 2.0 on 2018-08-21 17:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerStoreCredit',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='HistoricalCustomerStoreCredit',
            new_name='HistoricalCustomer',
        ),
        migrations.AlterModelOptions(
            name='historicalcustomer',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical customer'},
        ),
    ]
