# Generated by Django 2.0 on 2018-08-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20180821_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpreordersready',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpreordersready',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='preordersready',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='preordersready',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
    ]
