# Generated by Django 2.0 on 2018-08-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20180821_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customer Store Credit'},
        ),
        migrations.AlterModelOptions(
            name='preorder',
            options={'verbose_name_plural': 'Create Preorder Product'},
        ),
        migrations.AlterModelOptions(
            name='preordersready',
            options={'verbose_name_plural': 'Preorders'},
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='history_change_reason',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
