# Generated by Django 2.0 on 2018-08-22 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20180821_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preordersready',
            options={'verbose_name_plural': 'Manage Preorders'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='email',
            field=models.EmailField(db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalpreordersready',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpreordersready',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='preordersready',
            name='customer_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='preordersready',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='preordersready',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='preordersready',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.Preorder'),
        ),
    ]
