# Generated by Django 2.0 on 2018-08-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20180824_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=200),
        ),
    ]
