# Generated by Django 2.0 on 2018-08-25 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_auto_20180824_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 8, 24, 21, 54, 19, 435242), verbose_name='Order Placed')),
                ('contact', models.CharField(default='', max_length=50)),
                ('contact_type', models.CharField(default='', max_length=50, verbose_name='Contact @')),
                ('missing', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, verbose_name='Grand Total')),
                ('notes', models.TextField(default='')),
                ('order_link', models.URLField(blank=True, default='', max_length=2000)),
                ('order', models.TextField(default='')),
            ],
        ),
    ]
