# Generated by Django 2.0 on 2018-08-25 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_orderrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrequest',
            old_name='contact',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 25, 5, 16, 2, 742772), verbose_name='Order Placed'),
        ),
    ]
