# Generated by Django 2.0 on 2018-08-25 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_auto_20180825_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 25, 5, 22, 12, 442182), verbose_name='Order Placed'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='missing',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='No Price Available'),
        ),
    ]
