# Generated by Django 2.0 on 2018-09-06 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_auto_20180906_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='medal',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Commander Medals'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='medal',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Commander Medals'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 6, 11, 57, 8, 298541), verbose_name='Order Placed'),
        ),
    ]
