# Generated by Django 2.0 on 2018-09-06 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_auto_20180906_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, verbose_name='Credit'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='medal',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Medals'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, verbose_name='Credit'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='medal',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Medals'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 6, 14, 25, 34, 720065), verbose_name='Order Placed'),
        ),
    ]
