# Generated by Django 2.0 on 2018-09-10 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_auto_20180906_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 10, 12, 9, 50, 390928), verbose_name='Order Placed'),
        ),
    ]
