# Generated by Django 2.0 on 2018-09-11 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_auto_20180911_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releasedproducts',
            options={'verbose_name_plural': 'Released Products'},
        ),
        migrations.AddField(
            model_name='releasedproducts',
            name='month',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='releasedproducts',
            name='year',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 18, 23, 0, 604158), verbose_name='Order Placed'),
        ),
        migrations.AlterField(
            model_name='releasedproducts',
            name='release_date',
            field=models.CharField(default='Unknown', max_length=25, verbose_name='Release Date'),
        ),
    ]
