# Generated by Django 2.0 on 2018-09-15 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_auto_20180911_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 14, 22, 28, 42, 342794), verbose_name='Order Placed'),
        ),
    ]
