# Generated by Django 2.0 on 2018-09-15 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_auto_20180914_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 15, 6, 56, 54, 818792), verbose_name='Order Placed'),
        ),
    ]
