# Generated by Django 2.0 on 2018-09-15 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_auto_20180915_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 15, 10, 34, 6, 354969), verbose_name='Order Placed'),
        ),
    ]
