# Generated by Django 2.0 on 2018-09-18 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0036_auto_20180918_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 18, 17, 48, 58, 808107), verbose_name='Order Placed'),
        ),
    ]
