# Generated by Django 2.0 on 2018-09-21 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0039_auto_20180919_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 21, 14, 0, 19, 377940), verbose_name='Order Placed'),
        ),
    ]
