# Generated by Django 2.0 on 2018-09-22 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0040_auto_20180921_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 22, 12, 37, 44, 603138), verbose_name='Order Placed'),
        ),
    ]
