# Generated by Django 2.0 on 2018-10-11 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0043_auto_20181011_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 13, 27, 1, 572748), verbose_name='Order Placed'),
        ),
    ]
