# Generated by Django 2.0 on 2018-10-11 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0044_auto_20181011_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 13, 29, 18, 348674), verbose_name='Order Placed'),
        ),
    ]
