# Generated by Django 2.0 on 2018-10-12 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0046_auto_20181012_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tournament_results_credit',
            field=models.CharField(choices=[('none', 'None'), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40)], default='None', max_length=255, verbose_name='Tournament Credit'),
        ),
        migrations.AddField(
            model_name='historicalcustomer',
            name='tournament_results_credit',
            field=models.CharField(choices=[('none', 'None'), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40)], default='None', max_length=255, verbose_name='Tournament Credit'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 12, 13, 9, 20, 898595), verbose_name='Order Placed'),
        ),
    ]
