# Generated by Django 2.0 on 2018-10-25 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0050_auto_20181025_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 14, 44, 8, 376832), verbose_name='Order Placed'),
        ),
    ]
