# Generated by Django 2.0 on 2018-11-15 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0051_auto_20181025_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 19, 54, 16, 611512), verbose_name='Order Placed'),
        ),
    ]
