# Generated by Django 2.0 on 2018-11-15 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0062_auto_20181114_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 20, 51, 12, 647251), verbose_name='Order Placed'),
        ),
    ]
