# Generated by Django 2.0 on 2018-11-15 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0063_auto_20181114_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 21, 3, 40, 314420), verbose_name='Order Placed'),
        ),
    ]
