# Generated by Django 2.1.4 on 2018-12-17 19:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0066_auto_20181114_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpreordersready',
            name='customer_name',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer.Customer', verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='historicalpreordersready',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer.Preorder'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 17, 14, 34, 37, 479512), verbose_name='Order Placed'),
        ),
    ]
