# Generated by Django 2.1.4 on 2018-12-22 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0067_auto_20181217_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 17, 34, 30, 436587), verbose_name='Order Placed'),
        ),
    ]
