# Generated by Django 2.1.4 on 2018-12-24 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0069_auto_20181222_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 24, 11, 51, 32, 255426), verbose_name='Order Placed'),
        ),
    ]
