# Generated by Django 2.1.4 on 2018-12-24 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0070_auto_20181224_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 24, 12, 8, 31, 695669), verbose_name='Order Placed'),
        ),
    ]
