# Generated by Django 2.1.4 on 2018-12-26 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0071_auto_20181224_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 26, 17, 1, 11, 150647), verbose_name='Order Placed'),
        ),
    ]
