# Generated by Django 2.1.4 on 2019-01-19 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0079_auto_20190119_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 19, 15, 26, 51, 200088), verbose_name='Order Placed'),
        ),
    ]
