# Generated by Django 2.1.4 on 2019-01-23 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0087_auto_20190123_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 13, 15, 40, 478035), verbose_name='Order Placed'),
        ),
    ]
