# Generated by Django 2.1.4 on 2019-01-23 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0094_auto_20190123_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 15, 30, 31, 491649), verbose_name='Order Placed'),
        ),
    ]
