# Generated by Django 2.1.4 on 2019-01-24 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0099_auto_20190123_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 24, 16, 35, 6, 685239), verbose_name='Order Placed'),
        ),
    ]
