# Generated by Django 2.1.4 on 2019-02-06 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0100_auto_20190124_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 15, 32, 67459), verbose_name='Order Placed'),
        ),
    ]
