# Generated by Django 2.1.4 on 2019-02-06 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0101_auto_20190206_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 13, 26, 23, 244628), verbose_name='Order Placed'),
        ),
    ]
