# Generated by Django 2.1.4 on 2019-02-06 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0102_auto_20190206_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 13, 56, 36, 461554), verbose_name='Order Placed'),
        ),
    ]
