# Generated by Django 2.1.4 on 2019-02-06 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0104_auto_20190206_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 15, 28, 41, 879051), verbose_name='Order Placed'),
        ),
    ]
