# Generated by Django 2.1.4 on 2019-02-11 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0105_auto_20190206_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 11, 17, 28, 35, 592265), verbose_name='Order Placed'),
        ),
    ]
