# Generated by Django 2.1.4 on 2019-02-13 18:14

import datetime
from django.db import migrations, models
import validators.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0107_auto_20190211_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True, validators=[validators.model_validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=100, validators=[validators.model_validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 13, 13, 13, 59, 398180), verbose_name='Order Placed'),
        ),
    ]
