# Generated by Django 2.1.4 on 2019-02-16 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0109_auto_20190216_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 16, 8, 54, 51, 599863), verbose_name='Order Placed'),
        ),
    ]
