# Generated by Django 2.1.4 on 2019-02-18 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0110_auto_20190216_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 17, 25, 21, 977001), verbose_name='Order Placed'),
        ),
    ]
