# Generated by Django 2.1.4 on 2019-02-19 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0111_auto_20190218_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 20, 12, 27, 720131), verbose_name='Order Placed'),
        ),
    ]
