# Generated by Django 2.1.4 on 2019-02-19 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0113_auto_20190218_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 19, 8, 16, 3, 918872), verbose_name='Order Placed'),
        ),
    ]
