# Generated by Django 2.1.4 on 2019-02-20 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0118_auto_20190220_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 20, 18, 48, 33, 267042), verbose_name='Order Placed'),
        ),
    ]
