# Generated by Django 2.1.4 on 2019-02-25 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0122_auto_20190222_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 11, 7, 40, 745922), verbose_name='Order Placed'),
        ),
    ]
