# Generated by Django 2.1.4 on 2019-02-27 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0128_auto_20190226_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 8, 59, 2, 786471), verbose_name='Order Placed'),
        ),
    ]
