# Generated by Django 2.1.4 on 2019-02-27 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0129_auto_20190227_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 9, 15, 42, 657474), verbose_name='Order Placed'),
        ),
    ]
