# Generated by Django 2.1.4 on 2019-03-05 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0139_auto_20190303_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 5, 16, 53, 8, 83755), verbose_name='Order Placed'),
        ),
    ]
