# Generated by Django 2.1.4 on 2019-03-05 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0140_auto_20190305_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 5, 17, 9, 19, 5350), verbose_name='Order Placed'),
        ),
    ]
