# Generated by Django 2.1.4 on 2019-03-11 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0141_auto_20190305_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 19, 3, 48, 395185), verbose_name='Order Placed'),
        ),
    ]
