# Generated by Django 2.1.4 on 2019-03-11 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0142_auto_20190311_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 19, 29, 46, 884909), verbose_name='Order Placed'),
        ),
    ]
