# Generated by Django 2.1.4 on 2019-03-20 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0144_auto_20190320_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 16, 18, 40, 69644), verbose_name='Order Placed'),
        ),
    ]
