# Generated by Django 2.1.4 on 2019-03-20 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0145_auto_20190320_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 17, 25, 10, 636877), verbose_name='Order Placed'),
        ),
    ]
