# Generated by Django 2.1.4 on 2019-04-01 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0153_auto_20190401_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemizedpreorder',
            name='total_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 16, 50, 52, 609659), verbose_name='Order Placed'),
        ),
    ]
