# Generated by Django 2.1.4 on 2019-04-12 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0164_auto_20190411_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 22, 24, 20, 53197), verbose_name='Order Placed'),
        ),
    ]
