# Generated by Django 2.1.4 on 2019-04-12 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0174_auto_20190412_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 13, 6, 20, 86919), verbose_name='Order Placed'),
        ),
    ]
