# Generated by Django 2.1.4 on 2019-04-12 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0176_auto_20190412_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 13, 56, 26, 831652), verbose_name='Order Placed'),
        ),
    ]
