# Generated by Django 2.1.4 on 2019-04-14 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0177_auto_20190412_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemizedpreorder',
            name='card_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 16, 41, 15, 551343), verbose_name='Order Placed'),
        ),
    ]
