# Generated by Django 2.2.2 on 2019-07-23 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0178_auto_20190414_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 23, 13, 47, 12, 851451), verbose_name='Order Placed'),
        ),
    ]
