# Generated by Django 2.2.2 on 2019-07-26 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0180_auto_20190724_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 25, 23, 3, 34, 848420), verbose_name='Order Placed'),
        ),
    ]
