# Generated by Django 2.2.2 on 2019-07-26 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0181_auto_20190725_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 25, 23, 6, 1, 363410), verbose_name='Order Placed'),
        ),
    ]
