# Generated by Django 2.2.2 on 2019-07-29 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0185_auto_20190726_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 15, 35, 51, 940856), verbose_name='Order Placed'),
        ),
    ]
