# Generated by Django 2.2.2 on 2019-09-13 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0194_auto_20190907_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 13, 13, 50, 29, 239794), verbose_name='Order Placed'),
        ),
    ]
