# Generated by Django 2.2.2 on 2019-09-13 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0195_auto_20190913_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 13, 13, 53, 9, 622276), verbose_name='Order Placed'),
        ),
    ]
