# Generated by Django 2.2.2 on 2019-09-27 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0198_auto_20190913_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 27, 16, 43, 55, 650785), verbose_name='Order Placed'),
        ),
    ]
