# Generated by Django 2.2.2 on 2019-09-27 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0200_auto_20190927_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 27, 18, 24, 2, 885359), verbose_name='Order Placed'),
        ),
    ]
