# Generated by Django 2.2.2 on 2019-09-28 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0202_auto_20190928_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 17, 34, 22, 651379), verbose_name='Order Placed'),
        ),
    ]
