# Generated by Django 2.2.2 on 2019-10-19 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0204_auto_20191007_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 15, 26, 10, 445966), verbose_name='Order Placed'),
        ),
    ]
