# Generated by Django 2.2.2 on 2019-10-19 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0205_auto_20191019_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 15, 33, 33, 232303), verbose_name='Order Placed'),
        ),
    ]
