# Generated by Django 2.2.2 on 2019-11-09 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0207_auto_20191109_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 9, 12, 34, 32, 147878), verbose_name='Order Placed'),
        ),
    ]
