# Generated by Django 2.2.2 on 2019-11-19 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0209_auto_20191116_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 19, 42, 56, 818984), verbose_name='Order Placed'),
        ),
    ]
