# Generated by Django 2.2.2 on 2019-11-19 00:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0210_auto_20191118_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 19, 55, 23, 781078), verbose_name='Order Placed'),
        ),
    ]
