# Generated by Django 2.2.2 on 2019-11-19 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0213_auto_20191118_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 21, 52, 34, 77459), verbose_name='Order Placed'),
        ),
    ]
