# Generated by Django 2.2.2 on 2019-11-27 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0216_auto_20191125_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 13, 36, 50, 65815), verbose_name='Order Placed'),
        ),
    ]
