# Generated by Django 2.2.2 on 2019-12-18 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0223_auto_20191218_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 18, 16, 18, 353120), verbose_name='Order Placed'),
        ),
    ]
