# Generated by Django 2.2.2 on 2019-12-18 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0224_auto_20191218_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 18, 18, 28, 818754), verbose_name='Order Placed'),
        ),
    ]
