# Generated by Django 2.2.2 on 2019-12-19 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0226_auto_20191218_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 19, 49, 42, 956104), verbose_name='Order Placed'),
        ),
    ]
