# Generated by Django 2.2.2 on 2019-12-31 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0228_auto_20191230_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 11, 33, 54, 762795), verbose_name='Order Placed'),
        ),
    ]
