# Generated by Django 2.2.2 on 2020-01-06 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0233_auto_20200103_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 16, 7, 10, 183097), verbose_name='Order Placed'),
        ),
    ]
