# Generated by Django 2.2.2 on 2020-01-07 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0234_auto_20200106_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 20, 31, 31, 420103), verbose_name='Order Placed'),
        ),
    ]
