# Generated by Django 2.2.2 on 2020-01-08 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0235_auto_20200106_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 8, 13, 40, 43, 978587), verbose_name='Order Placed'),
        ),
    ]
