# Generated by Django 2.2.2 on 2020-01-08 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0236_auto_20200108_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 8, 13, 42, 6, 151939), verbose_name='Order Placed'),
        ),
    ]
