# Generated by Django 2.2.2 on 2019-11-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0004_cardkingdomanalytics_total_days_without_decrease'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarCityAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('expansion', models.CharField(default='', max_length=255)),
                ('printing', models.CharField(default='', max_length=255)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_percent_change', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_update', models.DateField(auto_now=True)),
                ('price_history', models.TextField(blank=True, default='')),
                ('consecutive_increase', models.IntegerField(default=0)),
                ('consecutive_decrease', models.IntegerField(default=0)),
                ('total_days_without_decrease', models.IntegerField(default=0)),
            ],
        ),
    ]
