# Generated by Django 2.0 on 2018-05-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('names', models.CharField(default='', max_length=200)),
                ('expansion', models.CharField(default='', max_length=50)),
                ('mana_cost', models.CharField(default='', max_length=50)),
                ('colors', models.CharField(default='', max_length=50)),
                ('color_identity', models.CharField(default='', max_length=50)),
                ('cmc', models.CharField(default='', max_length=50)),
                ('types', models.CharField(default='', max_length=50)),
                ('supertypes', models.CharField(default='', max_length=50)),
                ('subtypes', models.CharField(default='', max_length=50)),
                ('rarity', models.CharField(default='', max_length=50)),
                ('text', models.CharField(default='', max_length=50)),
                ('flavor', models.CharField(default='', max_length=50)),
                ('artist', models.CharField(default='', max_length=50)),
                ('number', models.CharField(default='', max_length=50)),
                ('power', models.CharField(default='', max_length=50)),
                ('toughness', models.CharField(default='', max_length=50)),
                ('layout', models.CharField(default='', max_length=50)),
                ('loyalty', models.CharField(default='', max_length=50)),
                ('multiverse_id', models.CharField(default='', max_length=50)),
                ('variations', models.CharField(default='', max_length=50)),
                ('borders', models.CharField(default='', max_length=50)),
                ('watermark', models.CharField(default='', max_length=50)),
                ('timeshifted', models.CharField(default='', max_length=50)),
                ('hand', models.CharField(default='', max_length=50)),
                ('life', models.CharField(default='', max_length=50)),
                ('release_date', models.CharField(default='', max_length=50)),
                ('starter', models.CharField(default='', max_length=50)),
                ('printings', models.CharField(default='', max_length=50)),
                ('original_text', models.CharField(default='', max_length=50)),
                ('original_type', models.CharField(default='', max_length=50)),
                ('source', models.CharField(default='', max_length=50)),
                ('image_url', models.CharField(default='', max_length=50)),
                ('set_name', models.CharField(default='', max_length=50)),
                ('card_id', models.CharField(default='', max_length=50)),
                ('legalities', models.CharField(default='', max_length=50)),
                ('rulings', models.CharField(default='', max_length=50)),
                ('foreign_names', models.CharField(default='', max_length=50)),
                ('site', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
