# Generated by Django 2.0 on 2018-05-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card_data',
            old_name='borders',
            new_name='border',
        ),
    ]
