# Generated by Django 2.0 on 2018-05-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_auto_20180529_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_data',
            name='foreign_names',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='card_data',
            name='legalities',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='card_data',
            name='printings',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='card_data',
            name='rulings',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='card_data',
            name='flavor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='card_data',
            name='original_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='card_data',
            name='starter',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='card_data',
            name='text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
