# Generated by Django 2.0 on 2018-06-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_auto_20180529_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('names', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=12)),
                ('expansion', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('mana_cost', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('colors', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('color_identity', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cmc', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('types', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('supertypes', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('subtypes', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('rarity', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('text', models.TextField(blank=True, default='', null=True)),
                ('flavor', models.TextField(blank=True, default='', null=True)),
                ('artist', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('power', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('toughness', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('layout', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('loyalty', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('multiverse_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('variations', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('border', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('watermark', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('timeshifted', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('hand', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('life', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('release_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('starter', models.TextField(blank=True, default='', null=True)),
                ('printings', models.TextField(blank=True, default='', null=True)),
                ('original_text', models.TextField(blank=True, default='', null=True)),
                ('original_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('set_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('card_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('legalities', models.TextField(blank=True, default='', null=True)),
                ('rulings', models.TextField(blank=True, default='', null=True)),
                ('foreign_names', models.TextField(blank=True, default='', null=True)),
                ('site', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Card_data',
        ),
    ]
