# Generated by Django 2.0 on 2018-06-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
