# Generated by Django 2.0 on 2018-06-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0013_auto_20180607_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
