# Generated by Django 2.0 on 2018-07-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0019_auto_20180630_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
