# Generated by Django 2.0 on 2018-07-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0020_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders_processing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('shipping_address', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('order_number', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('order_date', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('order_details', models.TextField(blank=True, default='', null=True)),
                ('direct', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('order_status_type', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('order_deliivery_type', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('order_channel_type', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('international', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('modified', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('token', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('product_cost', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('shipping_fee', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('gross_earnings', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
            ],
        ),
    ]
