# Generated by Django 2.0 on 2018-07-27 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0021_orders_processing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders_processing',
            old_name='direct',
            new_name='direct_order',
        ),
        migrations.RenameField(
            model_name='orders_processing',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='orders_processing',
            old_name='product_cost',
            new_name='product_value',
        ),
        migrations.RenameField(
            model_name='orders_processing',
            old_name='shipping_fee',
            new_name='shipping_paid',
        ),
        migrations.RemoveField(
            model_name='orders_processing',
            name='last_name',
        ),
    ]
