# Generated by Django 2.0 on 2018-07-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0022_auto_20180727_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_processing',
            name='shipping_address',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
