# Generated by Django 2.0 on 2018-07-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0027_auto_20180730_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders_ready',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status_type', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Order Status')),
                ('order_date', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Date Ordered')),
                ('shipping_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('order_number', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('order_details', models.TextField(blank=True, default='', null=True, verbose_name='Items Ordered')),
                ('shipping_address', models.TextField(blank=True, default='', null=True)),
                ('order_delivery_type', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('direct_order', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('order_channel_type', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('international', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('modified', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('token', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('product_value', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('shipping_paid', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('gross_earnings', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, verbose_name='Total Amount received')),
                ('fees', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
            ],
        ),
    ]
