# Generated by Django 2.0 on 2018-07-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0028_orders_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_processing',
            name='direct_order',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Order Channel'),
        ),
        migrations.AlterField(
            model_name='orders_processing',
            name='order_delivery_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Delivery Type'),
        ),
    ]
