# Generated by Django 2.0 on 2018-07-31 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0030_auto_20180731_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders_processing',
            name='orders_ready',
        ),
    ]
