# Generated by Django 2.0 on 2018-08-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0031_remove_orders_processing_orders_ready'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('expansion', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('condition', models.CharField(blank=True, default='', max_length=35, null=True)),
            ],
        ),
    ]
