# Generated by Django 2.0 on 2018-08-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0034_auto_20180801_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders_processing',
            name='direct_order',
        ),
        migrations.RemoveField(
            model_name='orders_processing',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orders_processing',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='orders_processing',
            name='gross_earnings',
        ),
        migrations.RemoveField(
            model_name='orders_processing',
            name='international',
        ),
        migrations.RemoveField(
            model_name='orders_processing',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='orders_processing',
            name='order_channel_type',
        ),
        migrations.RemoveField(
            model_name='orders_processing',
            name='product_value',
        ),
        migrations.RemoveField(
            model_name='orders_processing',
            name='shipping_paid',
        ),
        migrations.RemoveField(
            model_name='orders_processing',
            name='tax',
        ),
    ]
