# Generated by Django 2.0 on 2018-08-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0040_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status_type', models.CharField(blank=True, db_index=True, default='', max_length=50, null=True, verbose_name='Order Status')),
                ('order_date', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Date Ordered')),
                ('shipping_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('order_number', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('order_details', models.TextField(blank=True, default='', null=True, verbose_name='Items Ordered')),
                ('shipping_address', models.TextField(blank=True, default='', null=True)),
                ('order_delivery_type', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Delivery Type')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('token', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('product_value', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
            ],
        ),
    ]
