# Generated by Django 2.0 on 2018-08-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0043_foreignorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreignorder',
            name='name',
        ),
        migrations.RemoveField(
            model_name='foreignorder',
            name='net_profit',
        ),
        migrations.AlterField(
            model_name='foreignorder',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True),
        ),
    ]
