# Generated by Django 2.0 on 2018-08-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0044_auto_20180815_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='TcgCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(default='')),
            ],
        ),
    ]
