# Generated by Django 2.0 on 2018-08-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0048_auto_20180821_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
    ]
