# Generated by Django 2.0 on 2018-08-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0049_auto_20180822_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcgcredentials',
            name='name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
