# Generated by Django 2.0 on 2018-08-25 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0051_orderrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 24, 21, 51, 2, 2757), verbose_name='Order Placed'),
        ),
    ]
