# Generated by Django 2.0 on 2018-08-25 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0052_auto_20180824_2151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderRequest',
        ),
    ]
