# Generated by Django 2.0 on 2018-09-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0053_delete_orderrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatedInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('expansion', models.CharField(default='', max_length=255)),
                ('condition', models.CharField(default='', max_length=255)),
                ('is_foil', models.CharField(default='', max_length=10, verbose_name='FOil?')),
                ('previous_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, verbose_name='Previous Price')),
                ('updated_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, verbose_name='Updated Price')),
                ('change_date', models.CharField(default='Sat/15/2018', max_length=255, verbose_name='Price Changed on')),
            ],
        ),
    ]
