# Generated by Django 2.0 on 2018-09-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0055_auto_20180915_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatedinventory',
            name='sku',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Mon/17/2018', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
