# Generated by Django 2.0 on 2018-09-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0056_auto_20180917_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatedinventory',
            name='group_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
