# Generated by Django 2.0 on 2018-09-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0057_updatedinventory_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('expansion', models.CharField(default='', max_length=255)),
                ('price', models.CharField(default='', max_length=255)),
                ('sku', models.CharField(default='', max_length=255)),
                ('product_id', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Tue/18/2018', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
