# Generated by Django 2.0 on 2018-09-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0058_auto_20180918_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='casecards',
            name='Update_status',
            field=models.CharField(default='', max_length=4),
        ),
    ]
