# Generated by Django 2.0 on 2018-10-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0063_auto_20181002_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Thu/11/2018', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
