# Generated by Django 2.1.4 on 2018-12-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0070_auto_20181222_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedatabase',
            name='language',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
