# Generated by Django 2.1.4 on 2018-12-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0071_storedatabase_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedatabase',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Chinese (S)', 'Chinese (S)'), ('Chinese (T)', 'Chinese (T)'), ('Russian', 'Russian'), ('German', 'German'), ('Spanish', 'Spanish'), ('French', 'French'), ('Italian', 'Italian'), ('Portuguese', 'Portuguese')], db_index=True, default='English', max_length=255),
        ),
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Mon/24/2018', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
