# Generated by Django 2.1.4 on 2018-12-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0073_auto_20181226_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Sat/29/2018', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
