# Generated by Django 2.1.4 on 2019-01-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0078_auto_20190108_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='MtgDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=150)),
                ('expansion', models.CharField(default='', max_length=100)),
                ('product_id', models.CharField(default='', max_length=12)),
                ('image', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('custom_percentage', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Wed/23/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
