# Generated by Django 2.1.4 on 2019-02-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0082_auto_20190206_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Mon/11/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
