# Generated by Django 2.1.4 on 2019-02-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0088_auto_20190220_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtg',
            name='number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtg',
            name='product_name',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='name'),
        ),
    ]
