# Generated by Django 2.1.4 on 2019-02-21 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0091_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='quantity',
            new_name='upload_quantity',
        ),
        migrations.AddField(
            model_name='upload',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='upload',
            name='condition',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='upload',
            name='language',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='upload',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='upload',
            name='printing',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='upload',
            name='upload_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='upload_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='upload',
            name='upload_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Thu/21/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
