# Generated by Django 2.1.4 on 2019-02-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0094_auto_20190222_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, default='', max_length=255, verbose_name='name')),
                ('product_line', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('rarity', models.CharField(default='', max_length=255)),
                ('number', models.CharField(default='', max_length=255)),
                ('set_name', models.CharField(db_index=True, default='', max_length=255)),
                ('sku', models.CharField(default='', max_length=255)),
                ('condition', models.CharField(db_index=True, default='', max_length=255)),
                ('language', models.CharField(db_index=True, default='English', max_length=255)),
                ('foil', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Mon/25/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
