# Generated by Django 2.1.4 on 2019-02-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0098_auto_20190227_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='printing',
            field=models.CharField(default='', max_length=255, verbose_name='Foil'),
        ),
    ]
