# Generated by Django 2.1.4 on 2019-03-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0106_auto_20190325_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Sat/30/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
