# Generated by Django 2.1.4 on 2019-04-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0110_auto_20190404_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Sat/06/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
