# Generated by Django 2.1.4 on 2019-04-12 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0112_auto_20190412_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='engine.Location'),
        ),
    ]
