# Generated by Django 2.1.4 on 2019-04-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0113_events_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Sun/14/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
