# Generated by Django 2.2.2 on 2019-07-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0114_auto_20190414_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Tue/23/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
