# Generated by Django 2.2.2 on 2019-07-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0116_auto_20190724_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='directdata',
            name='last_consecutive_run',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='directdata',
            name='consecutive_days_non_direct',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='directdata',
            name='last_add',
            field=models.DateField(verbose_name='Last Non-direct Date'),
        ),
        migrations.AlterField(
            model_name='directdata',
            name='total_days_non_direct',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Thu/25/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
