# Generated by Django 2.2.2 on 2019-07-26 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0118_directdata_days_delta_direct_non_direct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directdata',
            old_name='days_delta_direct_non_direct',
            new_name='days_non_direct',
        ),
    ]
