# Generated by Django 2.2.2 on 2019-07-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0119_auto_20190725_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directdata',
            name='days_non_direct',
            field=models.IntegerField(default=1),
        ),
    ]
