# Generated by Django 2.2.2 on 2019-08-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0124_mooseinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooseinventory',
            name='updated_price',
            field=models.CharField(default='', max_length=255),
        ),
    ]
