# Generated by Django 2.2.2 on 2019-09-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0129_mooseautopricemetrics_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPriceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('expansion', models.CharField(default='', max_length=255)),
                ('tcg_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tcg_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amazon_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amazon_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('scg_buylist', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ck_buylist', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cfb_buylist', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
