# Generated by Django 2.2.2 on 2019-09-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0131_auto_20190927_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpricedata',
            name='sku',
            field=models.CharField(default='', max_length=255),
        ),
    ]
