# Generated by Django 2.2.2 on 2019-10-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0135_mtg_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtg',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
