# Generated by Django 2.2.2 on 2019-11-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0137_auto_20191116_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcggroupprice',
            name='foil',
        ),
        migrations.AddField(
            model_name='tcggroupprice',
            name='price_history',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tcggroupprice',
            name='printing',
            field=models.CharField(default='', max_length=255),
        ),
    ]
