# Generated by Django 2.2.2 on 2019-12-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0142_mtg_set_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtg',
            name='sku_list',
            field=models.CharField(default='', max_length=255),
        ),
    ]
