# Generated by Django 2.2.2 on 2019-12-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0144_cardpricedata_tcg_direct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpricedata',
            name='sell_to',
            field=models.CharField(default='', max_length=255),
        ),
    ]
