# Generated by Django 2.2.2 on 2020-01-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0146_cardpricedata_store_quantity_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtg',
            name='condition',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtg',
            name='language',
            field=models.CharField(default='English', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtg',
            name='product_id',
            field=models.CharField(db_index=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='mtg',
            name='product_name',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='mtg',
            name='set_abbreviation',
            field=models.CharField(default='', max_length=255),
        ),
    ]
