# Generated by Django 2.2.2 on 2020-01-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0147_auto_20200103_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpricedata',
            name='best_net',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cardpricedata',
            name='direct_net',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
