# Generated by Django 2.2.2 on 2020-01-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0150_auto_20200106_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpricedata',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
