# Generated by Django 2.2.2 on 2020-02-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageimage',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
