# Generated by Django 2.2.2 on 2020-02-24 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_homepageimage_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePageImage',
            new_name='HomePageLayout',
        ),
    ]
