# Generated by Django 3.0.5 on 2020-07-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0003_auto_20200224_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinglePrintingSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expansion', models.CharField(default='', max_length=255)),
                ('normal_only', models.BooleanField(default=False)),
                ('foil_only', models.BooleanField(default=False)),
            ],
        ),
    ]
