# Generated by Django 3.0.5 on 2020-09-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0004_singleprintingset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
