# Generated by Django 3.0.5 on 2020-09-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0005_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='clean_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
