# Generated by Django 3.0.5 on 2020-10-07 21:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0006_text_clean_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreorderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('expansion', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
