# Generated by Django 3.0.5 on 2020-10-07 22:13

from django.db import migrations, models
import validators.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0007_preorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorderitem',
            name='expansion',
            field=models.CharField(default='', max_length=255, validators=[validators.model_validators.correct_expansion_spelling]),
        ),
    ]
