# Generated by Django 3.0.5 on 2020-10-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0008_auto_20201007_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorderitem',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
