# Generated by Django 3.0.5 on 2020-10-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0011_privacypolicy_privacypolicyblock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name_plural': 'Privacy Policy'},
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='overview',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='reserved_right_clause',
            field=models.TextField(default='', max_length=255),
        ),
    ]
