# Generated by Django 3.0.5 on 2020-10-08 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0012_auto_20201008_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='effective_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='reserved_right_clause',
            field=models.TextField(default=''),
        ),
    ]
