# Generated by Django 3.0.5 on 2020-10-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0013_auto_20201008_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='effective_date',
            field=models.DateField(auto_now=True),
        ),
    ]
