# Generated by Django 3.0.5 on 2020-10-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0016_companyaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyaddress',
            options={'verbose_name_plural': 'Company Address'},
        ),
        migrations.RenameField(
            model_name='companyaddress',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='companyaddress',
            old_name='State',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
