# Generated by Django 2.0 on 2018-08-09 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0003_buying'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buying',
            name='image',
        ),
    ]
