# Generated by Django 2.0 on 2018-08-11 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0007_buying_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buying',
            old_name='condition',
            new_name='sku',
        ),
    ]
