# Generated by Django 2.0 on 2018-08-22 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0009_skulight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buying',
            options={'verbose_name_plural': 'Manage Buylist'},
        ),
    ]
