# Generated by Django 2.0 on 2018-09-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0010_auto_20180821_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='buying',
            name='condition',
            field=models.CharField(default='Unknown', max_length=250),
        ),
        migrations.AddField(
            model_name='buying',
            name='product_id',
            field=models.CharField(default='', max_length=250),
        ),
    ]
