# Generated by Django 2.0 on 2018-09-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0011_auto_20180919_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buying',
            name='product_id',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
