# Generated by Django 2.0 on 2018-10-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0013_auto_20180922_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('expansion', models.CharField(default='', max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('image', models.CharField(default='no_image.png', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'HotList',
            },
        ),
    ]
