# Generated by Django 2.0 on 2018-11-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0014_hotlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='buying',
            name='percentage',
            field=models.IntegerField(default=60),
        ),
    ]
