# Generated by Django 2.2.2 on 2019-10-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0021_auto_20190808_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardKingdomBuylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('expansion', models.CharField(default='', max_length=255)),
                ('is_foil', models.BooleanField(default=False)),
                ('price_nm', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_ex', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_vg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='StarcityBuylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('expansion', models.CharField(default='', max_length=255)),
                ('is_foil', models.BooleanField(default=False)),
                ('price_nm', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_played', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_hp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
