# Generated by Django 2.2.2 on 2019-12-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0025_storecredit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecredit',
            name='entries',
            field=models.IntegerField(default=0),
        ),
    ]
