# Generated by Django 3.0.5 on 2020-09-08 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0280_auto_20200824_1635'),
        ('buylist', '0029_auto_20200103_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuylistSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('expansion', models.CharField(default='', max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('buylist_order', models.TextField(default='')),
                ('buylist_status', models.BooleanField(default=False)),
                ('payment_type', models.BooleanField(default=False)),
                ('notes', models.TextField(default='')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
    ]
