# Generated by Django 3.0.5 on 2020-09-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0031_auto_20200911_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buylistsubmission',
            name='customer',
        ),
        migrations.AddField(
            model_name='buylistsubmission',
            name='address_line_1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='buylistsubmission',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='buylistsubmission',
            name='city',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='buylistsubmission',
            name='company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='buylistsubmission',
            name='country',
            field=models.CharField(blank=True, default='US', max_length=255),
        ),
        migrations.AddField(
            model_name='buylistsubmission',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='buylistsubmission',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='buylistsubmission',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='buylistsubmission',
            name='state',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='buylistsubmission',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
