# Generated by Django 3.0.5 on 2020-09-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0032_auto_20200911_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='buylistsubmission',
            name='paypal_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
