# Generated by Django 3.0.5 on 2020-09-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0037_auto_20200914_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='buylistsubmission',
            name='change_order_status',
            field=models.CharField(choices=[('not_received', 'Not Received'), ('verifying', 'Verifying Contents'), ('canceled', 'canceled'), ('processed', 'Processed')], default='', max_length=255),
        ),
    ]
