# Generated by Django 3.0.5 on 2020-09-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0040_auto_20200918_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotlist',
            name='printing',
            field=models.CharField(default='', max_length=255),
        ),
    ]
