# Generated by Django 3.0.5 on 2020-09-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0042_auto_20200928_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardkingdombuylist',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='starcitybuylist',
            name='product_id',
        ),
        migrations.AddField(
            model_name='hotlist',
            name='product_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
