# Generated by Django 3.0.5 on 2020-10-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0043_auto_20200928_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecredit',
            name='used_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
