# Generated by Django 3.0.5 on 2020-10-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0044_storecredit_used_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecredit',
            name='store_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Credit Added'),
        ),
        migrations.AlterField(
            model_name='storecredit',
            name='used_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Credit Used'),
        ),
    ]
