# Generated by Django 3.0.5 on 2020-10-21 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0045_auto_20201021_1719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreCredit',
        ),
    ]
