# Generated by Django 2.0 on 2018-08-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('set_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('condition', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('quantity', models.IntegerField(blank=True, default=20, null=True)),
                ('image', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
        ),
    ]
