# Generated by Django 2.0 on 2018-08-08 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buying',
        ),
    ]
