# Generated by Django 2.0 on 2018-08-09 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0038_auto_20180808_1726'),
        ('buylist', '0004_remove_buying_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='buying',
            name='image',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Product'),
        ),
    ]
