# Generated by Django 2.0 on 2018-08-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0008_auto_20180810_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('expansion', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('condition', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
