# Generated by Django 2.0 on 2018-11-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0015_buying_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buying',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.6, max_digits=4),
        ),
    ]
