# Generated by Django 2.0 on 2018-11-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0017_auto_20181114_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buying',
            name='percentage',
            field=models.FloatField(default=0.6),
        ),
    ]
