# Generated by Django 2.2.2 on 2019-08-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0020_auto_20181114_2051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buying',
        ),
        migrations.DeleteModel(
            name='SkuLight',
        ),
    ]
