# Generated by Django 2.2.2 on 2019-11-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0022_cardkingdombuylist_starcitybuylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardkingdombuylist',
            name='is_foil',
        ),
        migrations.RemoveField(
            model_name='starcitybuylist',
            name='is_foil',
        ),
        migrations.AddField(
            model_name='cardkingdombuylist',
            name='printing',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='starcitybuylist',
            name='printing',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
