# Generated by Django 2.2.2 on 2019-12-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0023_auto_20191118_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
            ],
        ),
    ]
