# Generated by Django 2.2.2 on 2019-12-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0024_storecredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecredit',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
