# Generated by Django 2.1.4 on 2019-02-16 13:46

from django.db import migrations, models
import validators.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orders_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScatterEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('none', 'None'), ('release_events', 'Release Events'), ('tcgplayer_kickback', 'TCGplayer Lickback'), ('ban_list_update', 'Ban-list Update'), ('special', 'Special')], default='None', max_length=255, validators=[validators.model_validators.validate_event_choice])),
                ('date', models.DateField()),
            ],
        ),
    ]
