# Generated by Django 2.1.4 on 2019-02-18 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190216_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='', max_length=255, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('expansion', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('condition', models.CharField(default='', max_length=255)),
                ('printing', models.CharField(default='', max_length=255)),
                ('language', models.CharField(default='', max_length=255)),
                ('category', models.CharField(default='', max_length=255)),
                ('rarity', models.CharField(default='', max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('last_upload_date', models.DateField(default=django.utils.timezone.now)),
                ('last_upload_quantity', models.IntegerField(default=0)),
                ('last_sold_date', models.DateField()),
                ('last_sold_quantity', models.IntegerField(default=0)),
                ('last_sold_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.AlterField(
            model_name='scatterevent',
            name='event',
            field=models.CharField(choices=[('none', 'None'), ('release_events', 'Release Events'), ('tcgplayer_kickback', 'TCGplayer Kickback'), ('ban_list_update', 'Ban-list Update'), ('special', 'Special')], default='None', max_length=255),
        ),
    ]
