# Generated by Django 2.1.4 on 2019-02-26 16:28

from django.db import migrations, models
import validators.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20190226_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='update_choice_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='update_item',
        ),
        migrations.AddField(
            model_name='inventory',
            name='update_inventory_quantity',
            field=models.IntegerField(default=0, validators=[validators.model_validators.confirm_quantity_sync]),
        ),
    ]
