# Generated by Django 2.1.4 on 2019-02-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20190226_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworders',
            name='customer_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
