# Generated by Django 2.1.4 on 2019-02-27 23:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_groupname_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(default=datetime.datetime(2019, 2, 27, 23, 16, 2, 420136, tzinfo=utc), verbose_name='Date')),
                ('inventory_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inventory_quantity', models.IntegerField(default=0)),
                ('total_of_english_mtg_foils_quantity', models.IntegerField(default=0)),
                ('total_of_english_mtg_foils', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_of_foreign_mtg_foils_quantity', models.IntegerField(default=0)),
                ('total_of_foreign_mtg_foils', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_of_foreign_mtg_quantity', models.IntegerField(default=0)),
                ('total_of_foreign_mtg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_of_english_mtg_quantity', models.IntegerField(default=0)),
                ('total_of_english_mtg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_of_mtg_sealed_product_quantity', models.IntegerField(default=0)),
                ('total_of_mtg_sealed_product', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_of_yugioh_quantity', models.IntegerField(default=0)),
                ('total_of_yugioh', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_of_pokemon_quantity', models.IntegerField(default=0)),
                ('total_of_pokemon', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_of_supplies_quantity', models.IntegerField(default=0)),
                ('total_of_supplies', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Inventory Analytics',
            },
        ),
    ]
