# Generated by Django 2.1.4 on 2019-02-27 23:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_inventoryanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryanalytics',
            name='check_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
