# Generated by Django 2.1.4 on 2019-03-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20190302_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryanalytics',
            name='total_of_mtg_sealed_product',
        ),
        migrations.RemoveField(
            model_name='inventoryanalytics',
            name='total_of_mtg_sealed_product_quantity',
        ),
        migrations.RemoveField(
            model_name='inventoryanalytics',
            name='total_of_supplies',
        ),
        migrations.RemoveField(
            model_name='inventoryanalytics',
            name='total_of_supplies_quantity',
        ),
        migrations.AddField(
            model_name='inventoryanalytics',
            name='inventory_quantity_over2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryanalytics',
            name='inventory_total_over2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryanalytics',
            name='total_of_english_mtg_foils_over2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryanalytics',
            name='total_of_english_mtg_foils_quantity_over2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryanalytics',
            name='total_of_english_mtg_over2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryanalytics',
            name='total_of_english_mtg_quantity_over2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryanalytics',
            name='total_of_foreign_mtg_foils_over2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryanalytics',
            name='total_of_foreign_mtg_foils_quantity_over2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryanalytics',
            name='total_of_foreign_mtg_over2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryanalytics',
            name='total_of_foreign_mtg_quantity_over2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryanalytics',
            name='total_of_others_over2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryanalytics',
            name='total_of_others_quantity_over2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryanalytics',
            name='total_of_pokemon_over2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryanalytics',
            name='total_of_pokemon_quantity_over2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryanalytics',
            name='total_of_yugioh_over2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryanalytics',
            name='total_of_yugioh_quantity_over2',
            field=models.IntegerField(default=0),
        ),
    ]
