# Generated by Django 2.1.4 on 2019-03-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_groupname_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='total_quantity_sold',
            field=models.IntegerField(default=0, verbose_name='Total Sold'),
        ),
    ]
