# Generated by Django 2.1.4 on 2019-03-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_inventory_ebay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='update_inventory_quantity',
            field=models.IntegerField(default=0, verbose_name='Increase or Decrease quantity'),
        ),
    ]
