# Generated by Django 2.1.4 on 2019-03-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20190325_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='amazon',
            field=models.BooleanField(default=False, verbose_name='On Amazon'),
        ),
    ]
