# Generated by Django 3.0.5 on 2020-04-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_inventory_tcg_direct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='InventoryAnalytics',
        ),
        migrations.DeleteModel(
            name='NewOrders',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='ScatterEvent',
        ),
    ]
