# Generated by Django 3.0.5 on 2020-06-01 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
