# Generated by Django 3.0.5 on 2020-06-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_orders_order_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=255)),
                ('clean_name', models.CharField(default='', max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
