# Generated by Django 3.0.5 on 2020-06-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_auto_20200606_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discounts_code_used',
            field=models.CharField(default='', max_length=255),
        ),
    ]
