# Generated by Django 3.0.5 on 2020-06-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='coupon',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
