# Generated by Django 3.0.5 on 2020-06-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_coupon_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='send_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
