# Generated by Django 3.0.5 on 2020-06-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_auto_20200620_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('data', models.TextField(default='')),
            ],
        ),
    ]
