# Generated by Django 3.0.5 on 2020-06-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payer_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
