# Generated by Django 3.0.5 on 2020-06-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0052_auto_20200629_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyToShipOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default='', max_length=255)),
                ('order_creation_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('', ''), ('shipped', 'shipped'), ('cancelled', 'cancelled')], default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('shipping_method', models.CharField(default='free', max_length=255)),
                ('address_line_1', models.CharField(default='', max_length=255)),
                ('address_line_2', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default='', max_length=255)),
                ('zip_code', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=255, null=True)),
                ('total_order_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('store_credit_used', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_charged', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_charged', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discounts_applied', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discounts_code_used', models.CharField(default='', max_length=255)),
                ('notes', models.TextField(default='')),
                ('ordered_items', models.TextField(default='')),
                ('order_view', models.URLField(default='')),
                ('send_message', models.TextField(blank=True, default='')),
                ('tracking_number', models.CharField(blank=True, default='', max_length=255)),
                ('payer_id', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
