# Generated by Django 3.0.5 on 2020-07-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0053_readytoshiporder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readytoshiporder',
            name='order_status',
            field=models.CharField(choices=[('', ''), ('ship', 'ship'), ('cancel', 'cancel')], default='', max_length=255),
        ),
    ]
