# Generated by Django 3.0.5 on 2020-07-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0056_auto_20200706_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_action',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
