# Generated by Django 3.0.5 on 2020-07-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0058_auto_20200715_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='completedorder',
            name='order_action',
            field=models.CharField(blank=True, choices=[('', '')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_action',
            field=models.CharField(blank=True, choices=[('', ''), ('cancel', 'cancel'), ('pull', 'move to pulling'), ('ship', 'mark as shipped')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('', ''), ('shipped', 'shipped'), ('ready_for_pickup', 'ready for pickup'), ('cancelled', 'cancelled'), ('pulling', 'pulling')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pendingpaymentorder',
            name='order_action',
            field=models.CharField(blank=True, choices=[('', ''), ('cancel', 'cancel'), ('open_order', 'move to open orders')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pullingorder',
            name='order_action',
            field=models.CharField(blank=True, choices=[('', ''), ('cancel', 'cancel'), ('ship', 'mark as shipped'), ('ready_to_ship', 'ready to ship')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='readytoshiporder',
            name='order_action',
            field=models.CharField(blank=True, choices=[('', ''), ('cancel', 'cancel'), ('ship', 'Mark as Shipped')], default='', max_length=255),
        ),
    ]
