# Generated by Django 3.0.5 on 2020-08-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0061_auto_20200824_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_paid', models.BooleanField(default=False)),
                ('order_number', models.CharField(default='', max_length=255)),
                ('order_creation_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('shipping_method', models.CharField(default='free', max_length=255)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='US', max_length=255)),
                ('address_line_1', models.CharField(default='', max_length=255)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default='', max_length=255)),
                ('zip_code', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('total_order_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('store_credit_used', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_charged', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_charged', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discounts_applied', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discounts_code_used', models.CharField(default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('ordered_items', models.TextField(default='')),
                ('order_view', models.URLField(default='')),
                ('send_message', models.TextField(blank=True, default='')),
                ('tracking_number', models.CharField(blank=True, default='', max_length=255)),
                ('payer_id', models.CharField(default='', max_length=255)),
                ('missing_cards', models.TextField(blank=True, default='')),
                ('order_status', models.CharField(choices=[('', ''), ('shipped', 'shipped'), ('ready_for_pickup', 'ready for pickup'), ('cancelled', 'cancelled'), ('pulling', 'pulling')], default='', max_length=255)),
                ('order_action', models.CharField(blank=True, choices=[('', ''), ('cancel', 'cancel'), ('pull', 'move to pulling'), ('ship', 'mark as shipped')], default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
