# Generated by Django 3.0.5 on 2020-09-02 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0062_preorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupname',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
