# Generated by Django 2.0 on 2018-05-30 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20180528_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_data',
            name='foreign_names',
        ),
        migrations.RemoveField(
            model_name='card_data',
            name='legalities',
        ),
        migrations.RemoveField(
            model_name='card_data',
            name='printings',
        ),
        migrations.RemoveField(
            model_name='card_data',
            name='rulings',
        ),
    ]
