# Generated by Django 2.0 on 2018-06-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0017_auto_20180626_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tcg_player_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
