# Generated by Django 2.0 on 2018-06-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0018_product_tcg_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tcg_player_id',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
