# Generated by Django 2.0 on 2018-07-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0023_auto_20180729_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_processing',
            name='direct_order',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
