# Generated by Django 2.0 on 2018-07-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0024_auto_20180730_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders_processing',
            old_name='order_deliivery_type',
            new_name='order_delivery_type',
        ),
    ]
