# Generated by Django 2.0 on 2018-07-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0025_auto_20180730_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_processing',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Cards Ordered'),
        ),
        migrations.AlterField(
            model_name='orders_processing',
            name='gross_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, verbose_name='Total Amount received'),
        ),
        migrations.AlterField(
            model_name='orders_processing',
            name='order_date',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Date Ordered'),
        ),
        migrations.AlterField(
            model_name='orders_processing',
            name='order_status_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Order Status'),
        ),
    ]
