# Generated by Django 2.0 on 2018-07-31 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0029_auto_20180731_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_processing',
            name='orders_ready',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='engine.Orders_ready'),
        ),
        migrations.AlterField(
            model_name='orders_processing',
            name='direct_order',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orders_processing',
            name='order_channel_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Order Channel'),
        ),
    ]
