# Generated by Django 2.0 on 2018-08-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0032_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
