# Generated by Django 2.0 on 2018-08-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0033_auto_20180801_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='expansion',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
