# Generated by Django 2.0 on 2018-08-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0035_auto_20180806_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_processing',
            name='orders_ready',
            field=models.ManyToManyField(to='engine.Orders_ready'),
        ),
    ]
