# Generated by Django 2.0 on 2018-08-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0036_orders_processing_orders_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True),
        ),
    ]
