# Generated by Django 2.0 on 2018-08-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0037_auto_20180808_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
