# Generated by Django 2.0 on 2018-08-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0039_auto_20180815_0805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
