# Generated by Django 2.0 on 2018-08-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0042_remove_orders_product_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('order_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('order_date', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Date Ordered')),
                ('cards', models.TextField(blank=True, default='', null=True, verbose_name='Items Ordered')),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
            ],
        ),
    ]
