# Generated by Django 2.0 on 2018-08-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0046_customer_historicalcustomer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='historicalcustomer',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalCustomer',
        ),
    ]
