# Generated by Django 2.0 on 2018-08-22 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0047_auto_20180820_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orders'},
        ),
    ]
