# Generated by Django 2.0 on 2018-09-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0059_casecards_update_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Wed/19/2018', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
