# Generated by Django 2.0 on 2018-10-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0064_auto_20181011_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Fri/12/2018', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
