# Generated by Django 2.0 on 2018-10-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0065_auto_20181012_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Thu/25/2018', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
