# Generated by Django 2.0 on 2018-11-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0066_auto_20181025_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignorder',
            name='mark',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Wed/14/2018', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
