# Generated by Django 2.0 on 2018-11-15 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0067_auto_20181114_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreignorder',
            name='mark',
        ),
    ]
