# Generated by Django 2.1.4 on 2018-12-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0068_remove_foreignorder_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='casecards',
            name='color',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Mon/17/2018', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
