# Generated by Django 2.1.4 on 2018-12-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0072_auto_20181224_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedatabase',
            name='condition',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='storedatabase',
            name='language',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Wed/26/2018', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
