# Generated by Django 2.1.4 on 2018-12-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0074_auto_20181229_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Mon/31/2018', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
