# Generated by Django 2.1.4 on 2019-01-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0077_auto_20190103_2040'),
    ]

    operations = [

        migrations.AlterField(
            model_name='storedatabase',
            name='condition',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Tue/08/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
