# Generated by Django 2.1.4 on 2019-01-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0077_auto_20190103_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('game', models.CharField(default='', max_length=255)),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12)),
                ('game_format', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='storedatabase',
            name='condition',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Tue/08/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
