# Generated by Django 2.1.4 on 2019-01-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0080_auto_20190123_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtgdatabase',
            name='rarity',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Thu/24/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
