# Generated by Django 2.1.4 on 2019-01-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0080_auto_20190123_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_s_damaged_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_s_damaged_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_s_damaged_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_s_heavily_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_s_heavily_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_s_heavily_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_s_lightly_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_s_lightly_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_s_lightly_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_s_moderately_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_s_moderately_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_s_moderately_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_s_near_mint_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_s_near_mint_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_s_near_mint_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_t_damaged_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_t_damaged_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_t_damaged_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_t_heavily_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_t_heavily_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_t_heavily_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_t_lightly_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_t_lightly_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_t_lightly_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_t_moderately_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_t_moderately_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_t_moderately_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_t_near_mint_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_t_near_mint_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='chinese_t_near_mint_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='english_damaged_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='english_damaged_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='english_damaged_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='english_heavily_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='english_heavily_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='english_heavily_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='english_lightly_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='english_lightly_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='english_lightly_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='english_moderately_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='english_moderately_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='english_moderately_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='english_near_mint_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='english_near_mint_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='english_near_mint_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_s_damaged_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_s_damaged_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_s_damaged_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_s_heavily_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_s_heavily_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_s_heavily_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_s_lightly_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_s_lightly_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_s_lightly_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_s_moderately_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_s_moderately_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_s_moderately_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_s_near_mint_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_s_near_mint_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_s_near_mint_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_t_damaged_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_t_damaged_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_t_damaged_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_t_heavily_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_t_heavily_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_t_heavily_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_t_lightly_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_t_lightly_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_t_lightly_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_t_moderately_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_t_moderately_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_t_moderately_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_t_near_mint_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_t_near_mint_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_chinese_t_near_mint_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_english_damaged_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_english_damaged_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_english_damaged_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_english_heavily_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_english_heavily_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_english_heavily_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_english_lightly_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_english_lightly_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_english_lightly_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_english_moderately_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_english_moderately_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_english_moderately_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_english_near_mint_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_english_near_mint_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_english_near_mint_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_french_damaged_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_french_damaged_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_french_damaged_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_french_heavily_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_french_heavily_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_french_heavily_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_french_lightly_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_french_lightly_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_french_lightly_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_french_moderately_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_french_moderately_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_french_moderately_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_french_near_mint_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_french_near_mint_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_french_near_mint_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_german_damaged_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_german_damaged_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_german_damaged_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_german_heavily_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_german_heavily_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_german_heavily_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_german_lightly_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_german_lightly_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_german_lightly_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_german_moderately_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_german_moderately_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_german_moderately_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_german_near_mint_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_german_near_mint_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_german_near_mint_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_italian_damaged_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_italian_damaged_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_italian_damaged_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_italian_heavily_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_italian_heavily_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_italian_heavily_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_italian_lightly_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_italian_lightly_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_italian_lightly_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_italian_moderately_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_italian_moderately_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_italian_moderately_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_italian_near_mint_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_italian_near_mint_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_italian_near_mint_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_japanese_damaged_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_japanese_damaged_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_japanese_damaged_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_japanese_heavily_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_japanese_heavily_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_japanese_heavily_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_japanese_lightly_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_japanese_lightly_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_japanese_lightly_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_japanese_moderately_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_japanese_moderately_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_japanese_moderately_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_japanese_near_mint_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_japanese_near_mint_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_japanese_near_mint_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_korean_damaged_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_korean_damaged_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_korean_damaged_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_korean_heavily_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_korean_heavily_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_korean_heavily_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_korean_lightly_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_korean_lightly_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_korean_lightly_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_korean_moderately_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_korean_moderately_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_korean_moderately_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_korean_near_mint_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_korean_near_mint_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_korean_near_mint_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_portuguese_damaged_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_portuguese_damaged_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_portuguese_damaged_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_portuguese_heavily_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_portuguese_heavily_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_portuguese_heavily_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_portuguese_lightly_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_portuguese_lightly_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_portuguese_lightly_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_portuguese_moderately_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_portuguese_moderately_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_portuguese_moderately_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_portuguese_near_mint_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_portuguese_near_mint_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_portuguese_near_mint_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_russian_damaged_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_russian_damaged_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_russian_damaged_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_russian_heavily_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_russian_heavily_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_russian_heavily_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_russian_lightly_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_russian_lightly_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_russian_lightly_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_russian_moderately_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_russian_moderately_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_russian_moderately_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_russian_near_mint_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_russian_near_mint_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_russian_near_mint_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_spanish_damaged_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_spanish_damaged_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_spanish_damaged_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_spanish_heavily_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_spanish_heavily_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_spanish_heavily_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_spanish_lightly_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_spanish_lightly_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_spanish_lightly_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_spanish_moderately_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_spanish_moderately_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_spanish_moderately_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_spanish_near_mint_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_spanish_near_mint_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_spanish_near_mint_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_chinese_s_damaged',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_chinese_s_heavily_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_chinese_s_lightly_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_chinese_s_moderately_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_chinese_s_near_mint',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_chinese_t_damaged',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_chinese_t_heavily_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_chinese_t_lightly_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_chinese_t_moderately_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_chinese_t_near_mint',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_english_damaged',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_english_heavily_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_english_lightly_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_english_moderately_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_english_near_mint',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_french_damaged',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_french_heavily_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_french_lightly_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_french_moderately_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_french_near_mint',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_german_damaged',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_german_heavily_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_german_lightly_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_german_moderately_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_german_near_mint',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_italian_damaged',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_italian_heavily_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_italian_lightly_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_italian_moderately_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_italian_near_mint',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_japanese_damaged',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_japanese_heavily_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_japanese_lightly_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_japanese_moderately_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_japanese_near_mint',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_korean_damaged',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_korean_heavily_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_korean_lightly_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_korean_moderately_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_korean_near_mint',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_portuguese_damaged',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_portuguese_heavily_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_portuguese_lightly_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_portuguese_moderately_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_portuguese_near_mint',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_russian_damaged',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_russian_heavily_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_russian_lightly_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_russian_moderately_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_russian_near_mint',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_spanish_damaged',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_spanish_heavily_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_spanish_lightly_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_spanish_moderately_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='foil_upload_price_spanish_near_mint',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='french_damaged_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='french_damaged_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='french_damaged_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='french_heavily_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='french_heavily_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='french_heavily_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='french_lightly_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='french_lightly_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='french_lightly_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='french_moderately_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='french_moderately_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='french_moderately_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='french_near_mint_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='french_near_mint_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='french_near_mint_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='german_damaged_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='german_damaged_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='german_damaged_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='german_heavily_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='german_heavily_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='german_heavily_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='german_lightly_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='german_lightly_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='german_lightly_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='german_moderately_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='german_moderately_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='german_moderately_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='german_near_mint_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='german_near_mint_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='german_near_mint_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='italian_damaged_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='italian_damaged_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='italian_damaged_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='italian_heavily_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='italian_heavily_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='italian_heavily_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='italian_lightly_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='italian_lightly_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='italian_lightly_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='italian_moderately_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='italian_moderately_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='italian_moderately_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='italian_near_mint_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='italian_near_mint_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='italian_near_mint_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='japanese_damaged_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='japanese_damaged_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='japanese_damaged_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='japanese_heavily_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='japanese_heavily_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='japanese_heavily_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='japanese_lightly_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='japanese_lightly_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='japanese_lightly_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='japanese_moderately_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='japanese_moderately_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='japanese_moderately_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='japanese_near_mint_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='japanese_near_mint_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='japanese_near_mint_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='korean_damaged_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='korean_damaged_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='korean_damaged_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='korean_heavily_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='korean_heavily_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='korean_heavily_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='korean_lightly_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='korean_lightly_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='korean_lightly_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='korean_moderately_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='korean_moderately_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='korean_moderately_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='korean_near_mint_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='korean_near_mint_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='korean_near_mint_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='portuguese_damaged_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='portuguese_damaged_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='portuguese_damaged_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='portuguese_heavily_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='portuguese_heavily_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='portuguese_heavily_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='portuguese_lightly_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='portuguese_lightly_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='portuguese_lightly_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='portuguese_moderately_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='portuguese_moderately_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='portuguese_moderately_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='portuguese_near_mint_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='portuguese_near_mint_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='portuguese_near_mint_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='russian_damaged_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='russian_damaged_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='russian_damaged_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='russian_heavily_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='russian_heavily_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='russian_heavily_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='russian_lightly_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='russian_lightly_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='russian_lightly_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='russian_moderately_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='russian_moderately_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='russian_moderately_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='russian_near_mint_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='russian_near_mint_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='russian_near_mint_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='spanish_damaged_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='spanish_damaged_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='spanish_damaged_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='spanish_heavily_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='spanish_heavily_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='spanish_heavily_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='spanish_lightly_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='spanish_lightly_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='spanish_lightly_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='spanish_moderately_played_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='spanish_moderately_played_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='spanish_moderately_played_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='spanish_near_mint_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='spanish_near_mint_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='spanish_near_mint_sku',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_chinese_s_damaged',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_chinese_s_heavily_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_chinese_s_lightly_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_chinese_s_moderately_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_chinese_s_near_mint',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_chinese_t_damaged',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_chinese_t_heavily_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_chinese_t_lightly_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_chinese_t_moderately_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_chinese_t_near_mint',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_english_damaged',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_english_heavily_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_english_lightly_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_english_moderately_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_english_near_mint',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_french_damaged',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_french_heavily_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_french_lightly_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_french_moderately_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_french_near_mint',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_german_damaged',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_german_heavily_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_german_lightly_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_german_moderately_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_german_near_mint',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_italian_damaged',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_italian_heavily_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_italian_lightly_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_italian_moderately_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_italian_near_mint',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_japanese_damaged',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_japanese_heavily_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_japanese_lightly_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_japanese_moderately_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_japanese_near_mint',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_korean_damaged',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_korean_heavily_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_korean_lightly_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_korean_moderately_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_korean_near_mint',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_portuguese_damaged',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_portuguese_heavily_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_portuguese_lightly_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_portuguese_moderately_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_portuguese_near_mint',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_russian_damaged',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_russian_heavily_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_russian_lightly_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_russian_moderately_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_russian_near_mint',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_spanish_damaged',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_spanish_heavily_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_spanish_lightly_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_spanish_moderately_played',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mtgdatabase',
            name='upload_price_spanish_near_mint',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mtgdatabase',
            name='condition_select',
            field=models.CharField(choices=[('near mint', 'Near Mint'), ('lightly played', 'Lightly played'), ('moderately played', 'Moderately played'), ('heavily played', 'Heavily played'), ('damaged', 'Damaged')], default='lightly played', max_length=20),
        ),
        migrations.AlterField(
            model_name='mtgdatabase',
            name='foil_select',
            field=models.CharField(choices=[('non-foil', 'Non-foil'), ('foil', 'foil')], default='non-foil', max_length=10),
        ),
        migrations.AlterField(
            model_name='mtgdatabase',
            name='language_select',
            field=models.CharField(choices=[('english', 'English'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('chinese (s)', 'Chinese (s)'), ('chinese (t)', 'Chinese (t)'), ('russian', 'Russian'), ('german', 'German'), ('spanish', 'Spanish'), ('italian', 'Italian'), ('french', 'French'), ('portuguese', 'Portuguese')], default='english', max_length=15),
        ),
    ]
