# Generated by Django 2.1.4 on 2019-01-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0081_auto_20190123_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtgdatabase',
            name='condition_select',
            field=models.CharField(choices=[('near mint', 'Near Mint'), ('lightly played', 'Lightly played'), ('moderately played', 'Moderately played'), ('heavily played', 'Heavily played'), ('damaged', 'Damaged')], default='Lightly played', max_length=20),
        ),
        migrations.AlterField(
            model_name='mtgdatabase',
            name='foil_select',
            field=models.CharField(choices=[('non-foil', 'Non-foil'), ('foil', 'foil')], default='non-foil', max_length=10),
        ),
        migrations.AlterField(
            model_name='mtgdatabase',
            name='language_select',
            field=models.CharField(choices=[('english', 'English'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('chinese (s)', 'Chinese (s)'), ('chinese (t)', 'Chinese (t)'), ('russian', 'Russian'), ('german', 'German'), ('spanish', 'Spanish'), ('italian', 'Italian'), ('french', 'French'), ('portuguese', 'Portuguese')], default='English', max_length=15),
        ),
    ]
