# Generated by Django 2.1.4 on 2019-01-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0081_auto_20190123_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtgdatabase',
            name='condition_select',
            field=models.CharField(choices=[('lightly played', 'Lightly played'), ('near mint', 'Near Mint'), ('moderately played', 'Moderately played'), ('heavily played', 'Heavily played'), ('damaged', 'Damaged')], default='lightly played', max_length=20),
        ),
    ]
