# Generated by Django 2.1.4 on 2019-02-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0083_auto_20190211_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Wed/13/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
