# Generated by Django 2.1.4 on 2019-02-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0085_auto_20190216_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Mon/18/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
