# Generated by Django 2.1.4 on 2019-02-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0086_auto_20190218_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Tue/19/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
