# Generated by Django 2.1.4 on 2019-02-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0089_auto_20190220_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtg',
            name='foil',
            field=models.BooleanField(default=False),
        ),
    ]
