# Generated by Django 2.1.4 on 2019-01-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0090_auto_20190123_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maindatabase',
            name='english_damaged_price',
        ),
        migrations.RemoveField(
            model_name='maindatabase',
            name='english_damaged_quantity',
        ),
        migrations.RemoveField(
            model_name='maindatabase',
            name='english_damaged_sku',
        ),
        migrations.RemoveField(
            model_name='maindatabase',
            name='english_heavily_played_price',
        ),
        migrations.RemoveField(
            model_name='maindatabase',
            name='english_heavily_played_quantity',
        ),
        migrations.RemoveField(
            model_name='maindatabase',
            name='english_heavily_played_sku',
        ),
        migrations.RemoveField(
            model_name='maindatabase',
            name='english_lightly_played_price',
        ),
        migrations.RemoveField(
            model_name='maindatabase',
            name='english_lightly_played_quantity',
        ),
        migrations.RemoveField(
            model_name='maindatabase',
            name='english_lightly_played_sku',
        ),
        migrations.RemoveField(
            model_name='maindatabase',
            name='english_moderately_played_price',
        ),
        migrations.RemoveField(
            model_name='maindatabase',
            name='english_moderately_played_quantity',
        ),
        migrations.RemoveField(
            model_name='maindatabase',
            name='english_moderately_played_sku',
        ),
        migrations.RemoveField(
            model_name='maindatabase',
            name='english_near_mint_price',
        ),
        migrations.RemoveField(
            model_name='maindatabase',
            name='english_near_mint_quantity',
        ),
        migrations.RemoveField(
            model_name='maindatabase',
            name='english_near_mint_sku',
        ),
    ]
