# Generated by Django 2.1.4 on 2019-01-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0091_auto_20190123_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maindatabase',
            name='condition_select',
        ),
        migrations.RemoveField(
            model_name='maindatabase',
            name='foil_select',
        ),
        migrations.RemoveField(
            model_name='maindatabase',
            name='language_select',
        ),
    ]
