# Generated by Django 2.1.4 on 2019-02-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0092_auto_20190221_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='group_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
