# Generated by Django 2.1.4 on 2019-02-26 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0096_auto_20190226_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'verbose_name_plural': 'Upload'},
        ),
    ]
