# Generated by Django 2.1.4 on 2019-02-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0099_auto_20190227_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Thu/28/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
