# Generated by Django 2.1.4 on 2019-03-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0100_auto_20190228_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Sat/02/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
