# Generated by Django 2.1.4 on 2019-03-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0101_auto_20190302_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Sun/03/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
