# Generated by Django 2.1.4 on 2019-03-05 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0102_auto_20190303_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='upload_card',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='engine.MTG'),
        ),
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Tue/05/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
