# Generated by Django 2.1.4 on 2019-03-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0104_auto_20190320_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtg',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mtg',
            name='product_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='mtgforeign',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mtgforeign',
            name='product_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Sat/23/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
