# Generated by Django 2.1.4 on 2019-03-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0105_auto_20190323_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Mon/25/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
