# Generated by Django 2.1.4 on 2019-04-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0108_auto_20190401_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Tue/02/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
