# Generated by Django 2.1.4 on 2019-04-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0109_auto_20190402_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Thu/04/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
