# Generated by Django 2.1.4 on 2019-04-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0111_auto_20190406_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('street_address', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default='', max_length=2)),
                ('zip_code', models.IntegerField(default=0)),
                ('phone', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Fri/12/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
