# Generated by Django 2.1.4 on 2019-04-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0112_auto_20190412_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('game', models.CharField(default='', max_length=255)),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12)),
                ('game_format', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('prize_support', models.TextField(default='Coming Soon')),
            ],
        ),
    ]
