# Generated by Django 2.1.4 on 2019-04-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0113_events_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='location',
        ),
        migrations.AddField(
            model_name='events',
            name='prize_support',
            field=models.TextField(default='Coming Soon'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
