# Generated by Django 2.1.4 on 2019-04-12 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0113_events_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='engine.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
