# Generated by Django 2.1.4 on 2019-04-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0114_auto_20190411_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='prize_support',
            field=models.TextField(default='Coming Soon'),
        ),
    ]
