# Generated by Django 2.2.2 on 2019-07-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0117_auto_20190725_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='directdata',
            name='days_delta_direct_non_direct',
            field=models.IntegerField(default=0),
        ),
    ]
