# Generated by Django 2.2.2 on 2019-07-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0120_auto_20190725_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='TcgGroupPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('expansion', models.CharField(default='', max_length=255)),
                ('foil', models.BooleanField(default=False)),
                ('low_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mid_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('market_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('direct_low_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_direct', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Fri/26/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
