# Generated by Django 2.2.2 on 2019-07-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0121_auto_20190726_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcggroupprice',
            name='product_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='updatedinventory',
            name='change_date',
            field=models.CharField(default='Mon/29/2019', max_length=255, verbose_name='Price Changed on'),
        ),
    ]
