# Generated by Django 2.2.2 on 2019-08-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0122_auto_20190729_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseCards',
        ),
        migrations.RemoveField(
            model_name='events',
            name='location',
        ),
        migrations.DeleteModel(
            name='ForeignOrder',
        ),
        migrations.DeleteModel(
            name='MtgDatabase',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sku',
        ),
        migrations.DeleteModel(
            name='UpdatedInventory',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
