# Generated by Django 2.2.2 on 2019-08-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0123_auto_20190808_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='MooseInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('expansion', models.CharField(default='', max_length=255)),
                ('condition', models.CharField(default='', max_length=255)),
                ('printing', models.CharField(default='', max_length=255)),
                ('seller_1_name', models.CharField(default='', max_length=255)),
                ('seller_1_total_sales', models.CharField(default='', max_length=255)),
                ('seller_1_total_price', models.CharField(default='', max_length=255)),
                ('seller_2_name', models.CharField(default='', max_length=255)),
                ('seller_2_total_sales', models.CharField(default='', max_length=255)),
                ('seller_2_total_price', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
