# Generated by Django 2.2.2 on 2019-09-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0127_mooseautopricemetrics_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooseautopricemetrics',
            name='sku',
            field=models.CharField(default='', max_length=255),
        ),
    ]
