# Generated by Django 2.2.2 on 2019-09-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0130_cardpricedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpricedata',
            name='amazon_net',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cardpricedata',
            name='amazon_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cardpricedata',
            name='cfb_buylist',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cardpricedata',
            name='ck_buylist',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cardpricedata',
            name='expansion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cardpricedata',
            name='scg_buylist',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cardpricedata',
            name='tcg_net',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cardpricedata',
            name='tcg_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
