# Generated by Django 2.2.2 on 2019-09-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0132_cardpricedata_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpricedata',
            name='product_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
