# Generated by Django 2.2.2 on 2019-09-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0133_cardpricedata_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpricedata',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
