# Generated by Django 2.2.2 on 2019-11-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0140_auto_20191130_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtg',
            name='card_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mtg',
            name='subtypes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
