# Generated by Django 2.2.2 on 2019-12-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0145_cardpricedata_sell_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpricedata',
            name='store_quantity_needed',
            field=models.IntegerField(default=0),
        ),
    ]
