# Generated by Django 2.2.2 on 2020-01-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0149_cardpricedata_tcg_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpricedata',
            name='low_store_stock',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=3),
        ),
    ]
