# Generated by Django 2.2.2 on 2020-01-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0151_cardpricedata_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='directdata',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
