# Generated by Django 2.2.2 on 2020-01-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0152_directdata_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='directdata',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='directdata',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='directdata',
            name='market',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
