# Generated by Django 2.2.2 on 2020-02-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0153_auto_20200120_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtg',
            name='product_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='mtg',
            name='product_name',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='name'),
        ),
    ]
