# Generated by Django 2.2.2 on 2020-03-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0154_auto_20200224_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mtg',
            old_name='price',
            new_name='clean_price',
        ),
        migrations.RenameField(
            model_name='mtg',
            old_name='stock',
            new_name='clean_stock',
        ),
        migrations.AddField(
            model_name='mtg',
            name='heavily_played_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='mtg',
            name='heavily_played_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mtg',
            name='played_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='mtg',
            name='played_stock',
            field=models.IntegerField(default=0),
        ),
    ]
