# Generated by Django 2.2.2 on 2020-04-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0155_auto_20200324_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mtg',
            old_name='set_name',
            new_name='expansion',
        ),
        migrations.RenameField(
            model_name='mtg',
            old_name='clean_price',
            new_name='foil_clean_price',
        ),
        migrations.RenameField(
            model_name='mtg',
            old_name='clean_stock',
            new_name='foil_clean_stock',
        ),
        migrations.RenameField(
            model_name='mtg',
            old_name='heavily_played_price',
            new_name='foil_heavily_played_price',
        ),
        migrations.RenameField(
            model_name='mtg',
            old_name='heavily_played_stock',
            new_name='foil_heavily_played_stock',
        ),
        migrations.RenameField(
            model_name='mtg',
            old_name='played_price',
            new_name='foil_played_price',
        ),
        migrations.RenameField(
            model_name='mtg',
            old_name='played_stock',
            new_name='foil_played_stock',
        ),
        migrations.RenameField(
            model_name='mtg',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='mtg',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='mtg',
            name='foil',
        ),
        migrations.RemoveField(
            model_name='mtg',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='mtg',
            name='sku_list',
        ),
        migrations.AddField(
            model_name='mtg',
            name='normal_clean_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='mtg',
            name='normal_clean_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mtg',
            name='normal_heavily_played_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='mtg',
            name='normal_heavily_played_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mtg',
            name='normal_played_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='mtg',
            name='normal_played_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mtg',
            name='oracle_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
