# Generated by Django 2.2.2 on 2020-04-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0156_auto_20200414_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtg',
            name='rarity',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtg',
            name='set_abbreviation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
