# Generated by Django 2.2.2 on 2020-04-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0157_auto_20200414_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='MtgCardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('card_identifier', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
