# Generated by Django 3.0.5 on 2020-04-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0158_mtgcardinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MtgForeign',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Pokemon',
        ),
        migrations.DeleteModel(
            name='StoreDatabase',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.DeleteModel(
            name='Yugioh',
        ),
        migrations.AlterModelOptions(
            name='mtg',
            options={'verbose_name_plural': 'MTG Card Database'},
        ),
    ]
