# Generated by Django 3.0.5 on 2020-04-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0159_auto_20200427_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mtg',
            options={'ordering': ['expansion', 'name'], 'verbose_name_plural': 'MTG Card Database'},
        ),
        migrations.AlterField(
            model_name='mtg',
            name='converted_mana_cost',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mtg',
            name='power',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mtg',
            name='toughness',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
