# Generated by Django 3.0.5 on 2020-05-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0161_mtg_svg_mana_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtg',
            name='svg_mana_cost',
        ),
        migrations.AddField(
            model_name='mtg',
            name='mana_cost_encoded',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
