# Generated by Django 3.0.5 on 2020-05-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0274_customerrestocknotice'),
        ('engine', '0162_auto_20200507_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtg',
            name='restock_notice',
            field=models.ManyToManyField(to='customer.CustomerRestockNotice'),
        ),
    ]
