# Generated by Django 3.0.5 on 2020-06-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0164_auto_20200606_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtg',
            name='normal_clean_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mtg',
            name='normal_heavily_played_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mtg',
            name='normal_played_stock',
            field=models.IntegerField(default=0),
        ),
    ]
