# Generated by Django 3.0.5 on 2020-07-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0165_auto_20200606_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMtgNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('link', models.URLField(default='')),
                ('description', models.TextField(default='')),
                ('published_date', models.CharField(default='', max_length=255)),
                ('creator', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
