# Generated by Django 3.0.5 on 2020-07-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0166_dailymtgnews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mtgcardinfo',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='mtg',
            name='foil_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mtg',
            name='normal_only',
            field=models.BooleanField(default=False),
        ),
    ]
