# Generated by Django 3.0.5 on 2020-08-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0279_auto_20200706_1819'),
        ('engine', '0167_auto_20200727_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mtg',
            options={'ordering': ['name'], 'verbose_name_plural': 'MTG Card Database'},
        ),
        migrations.AlterField(
            model_name='mtg',
            name='restock_notice',
            field=models.ManyToManyField(blank=True, to='customer.CustomerRestockNotice'),
        ),
    ]
