# Generated by Django 3.0.5 on 2020-08-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0168_auto_20200804_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTGUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=255, verbose_name='name')),
                ('expansion', models.CharField(db_index=True, default='', max_length=255)),
                ('product_id', models.CharField(default='', max_length=30)),
                ('normal_clean_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('normal_clean_stock', models.IntegerField(default=0)),
                ('normal_played_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('normal_played_stock', models.IntegerField(default=0)),
                ('normal_heavily_played_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('normal_heavily_played_stock', models.IntegerField(default=0)),
                ('foil_clean_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('foil_clean_stock', models.IntegerField(default=0)),
                ('foil_played_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('foil_played_stock', models.IntegerField(default=0)),
                ('foil_heavily_played_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('foil_heavily_played_stock', models.IntegerField(default=0)),
            ],
        ),
    ]
