# Generated by Django 3.0.5 on 2020-08-04 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0169_mtgupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtgupload',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mtgupload',
            name='upload_status',
            field=models.BooleanField(default=False),
        ),
    ]
