# Generated by Django 3.0.5 on 2020-08-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0171_copybasicinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CopyBasicInfo',
        ),
    ]
