# Generated by Django 3.0.5 on 2020-08-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0172_delete_copybasicinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('abbreviation', models.CharField(default='', max_length=2)),
                ('state_tax_rate', models.DecimalField(decimal_places=5, default=0, max_digits=12)),
                ('local_tax_rate', models.DecimalField(decimal_places=5, default=0, max_digits=12)),
            ],
        ),
    ]
