# Generated by Django 3.0.5 on 2020-08-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0173_stateinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtg',
            name='preorder',
            field=models.BooleanField(default=False),
        ),
    ]
