# Generated by Django 3.0.5 on 2020-08-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0174_mtg_preorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtg',
            name='solid_color',
            field=models.CharField(default='', max_length=255),
        ),
    ]
