# Generated by Django 3.0.5 on 2020-08-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0176_mtgdatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtgdatabase',
            name='product_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
