# Generated by Django 3.0.5 on 2020-09-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0179_auto_20200902_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtg',
            name='buylist_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
