# Generated by Django 3.0.5 on 2020-09-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0181_mtg_buylist_max_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mtg',
            old_name='buylist',
            new_name='foil_buylist',
        ),
        migrations.RenameField(
            model_name='mtg',
            old_name='buylist_max_quantity',
            new_name='foil_buylist_max_quantity',
        ),
        migrations.RenameField(
            model_name='mtg',
            old_name='buylist_price',
            new_name='foil_buylist_price',
        ),
        migrations.AddField(
            model_name='mtg',
            name='normal_buylist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mtg',
            name='normal_buylist_max_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mtg',
            name='normal_buylist_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
