# Generated by Django 3.0.5 on 2020-09-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0182_auto_20200909_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtg',
            name='hotlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mtg',
            name='hotlist_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
