# Generated by Django 3.0.5 on 2020-09-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0185_sickdeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sickdeal',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
