# Generated by Django 3.0.5 on 2020-09-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0187_auto_20200928_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mtg',
            old_name='sick_deal_price',
            new_name='sick_deal_percentage',
        ),
    ]
