# Generated by Django 3.0.5 on 2020-10-29 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0188_auto_20200928_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtg',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
