# Generated by Django 3.0.5 on 2020-10-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0189_mtg_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtg',
            name='solid_color',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
