# Generated by Django 3.0.5 on 2020-10-30 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0190_auto_20201030_1931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SickDeal',
        ),
    ]
