# Generated by Django 3.0.5 on 2020-11-09 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0193_auto_20201109_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcggroupprice',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
