# Generated by Django 3.0.5 on 2020-11-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0194_tcggroupprice_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcggroupprice',
            name='expansion',
        ),
        migrations.RemoveField(
            model_name='tcggroupprice',
            name='name',
        ),
    ]
