# Generated by Django 3.0.5 on 2020-11-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0196_auto_20201110_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpricedata',
            name='product_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
