# Generated by Django 3.0.5 on 2020-12-02 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0197_auto_20201110_1423'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DirectData',
        ),
    ]
