# Generated by Django 2.1.4 on 2019-03-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebayaccesstoken',
            old_name='token',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='ebayaccesstoken',
            name='refresh_token',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ebayaccesstoken',
            name='user_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
