# Generated by Django 2.1.4 on 2019-03-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0002_auto_20190320_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebayaccesstoken',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
