# Generated by Django 2.1.4 on 2019-03-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0003_auto_20190320_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaylisting',
            name='offer_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
